//! Generate the rs-lane `host_lookup.rs` by joining a title's symbol dump
//! against `fn64_abi::recompiled::ADAPTER_NAMES` (the authoritative host
//! adapter surface).
//!
//! The rs lane resolves host (libultra) functions BY ADDRESS: a small table
//! maps each libultra vram to fn64's typed adapter for that OS call. That
//! table used to be hand-maintained per title (`recomps/.../host_lookup.rs`)
//! and rotted — it referenced a since-renamed crate (`fn64_recomp_rs`) and
//! adapter names that had moved, so `FN64_RECOMP=rs` stopped compiling for
//! OoT. Deriving it here from the two things that ARE current — the emitted
//! crate's own symbol dump and `ADAPTER_NAMES` — means it can never drift
//! again: every arm names an adapter that provably exists, and every libultra
//! symbol the title actually has gets its real address.
//!
//! The join key: a libultra symbol name (`osInitialize`, `__ll_div`) maps to
//! an adapter name (`os_initialize`, `ll_div`) by stripping a leading `__` and
//! converting camelCase to snake_case. `ADAPTER_NAMES` is the ground truth for
//! which snake name is canonical (there are `os_initialize` variants, but only
//! the plain adapter is in the table), so we match against the SET rather than
//! trusting a name transform to be unique.

use std::collections::BTreeMap;

/// Convert a libultra symbol name to its adapter snake-case form:
/// strip one leading `__`, then insert `_` before each interior uppercase run
/// and lowercase everything. `osInitialize` -> `os_initialize`,
/// `__ll_div` -> `ll_div`, `osAiSetNextBuffer` -> `os_ai_set_next_buffer`,
/// `osEPiStartDma` -> `os_epi_start_dma`.
pub fn adapter_name_of(symbol: &str) -> String {
    let s = symbol.strip_prefix("__").unwrap_or(symbol);
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase() {
            // Boundary before an uppercase char ONLY when the previous char is
            // lowercase or a digit. An uppercase RUN stays one token, so the
            // hand-chosen adapter names that keep acronyms whole are matched
            // exactly: `osEPiStartDma` -> `os_epi_start_dma` (not
            // `os_e_pi_...`), `__osSiRawStartDma` -> `os_si_raw_start_dma`.
            let prev_lower = i > 0 && (chars[i - 1].is_ascii_lowercase() || chars[i - 1].is_ascii_digit());
            if prev_lower && !out.ends_with('_') {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// Join `(symbol_name, vram)` pairs against the adapter-name set. Returns the
/// resolved `(vram, adapter_name)` arms, sorted by vram, deduped (a symbol
/// name appearing once). A symbol whose adapter form is not in `adapters` is
/// simply not a host call — it stays in the recompiled crate.
pub fn resolve_arms(
    symbols: impl IntoIterator<Item = (String, u32)>,
    adapters: &[&str],
) -> Vec<(u32, String)> {
    let adapter_set: std::collections::BTreeSet<&str> = adapters.iter().copied().collect();
    // BTreeMap keyed by vram dedupes + sorts; last write wins but a vram maps
    // to exactly one symbol in a real dump.
    let mut arms: BTreeMap<u32, String> = BTreeMap::new();
    for (name, vram) in symbols {
        let adapter = adapter_name_of(&name);
        if adapter_set.contains(adapter.as_str()) {
            arms.insert(vram, adapter);
        }
    }
    arms.into_iter().collect()
}

/// Render the full `host_lookup.rs` file body. Matches the shape the shell's
/// `main.rs` includes: `exact_host_lookup` / `host_only_lookup` /
/// `recompiled_or_host_lookup`, using the current crate names
/// (`fn64_cpu_runtime::RecompFunc`, `crate::recompiled`).
pub fn render(arms: &[(u32, String)]) -> String {
    let mut s = String::new();
    s.push_str(
        "//! GENERATED by fn64-cpu-runtime-codegen host_lookup_gen — do not edit.\n\
         //! OoT-style rs-lane host-first lookup: libultra vram -> fn64-abi typed\n\
         //! adapter, joined from the title's symbol dump against\n\
         //! `fn64_abi::recompiled::ADAPTER_NAMES`.\n\n",
    );
    s.push_str("#[cfg(fn64_cpu_runtime)]\nuse crate::recompiled;\n\n");
    s.push_str("fn exact_host_lookup(vram: u32) -> Option<fn64_cpu_runtime::RecompFunc> {\n");
    s.push_str("    use fn64_abi::recompiled as r;\n");
    s.push_str("    let host = match vram {\n");
    for (vram, adapter) in arms {
        s.push_str(&format!("        {:#010X} => r::{adapter},\n", vram));
    }
    s.push_str("        _ => return None,\n");
    s.push_str("    };\n    Some(host)\n}\n\n");
    s.push_str(
        "pub fn host_only_lookup(vram: u32) -> Option<fn64_cpu_runtime::RecompFunc> {\n\
         \x20   exact_host_lookup(vram).or_else(|| {\n\
         \x20       let canonical = fn64_abi::recompiled::canonical_vram(vram)?;\n\
         \x20       exact_host_lookup(canonical)\n\
         \x20   })\n}\n\n",
    );
    s.push_str(
        "#[cfg(fn64_cpu_runtime)]\n\
         pub fn recompiled_or_host_lookup(vram: u32) -> Option<fn64_cpu_runtime::RecompFunc> {\n\
         \x20   if let Some(host) = host_only_lookup(vram) {\n\
         \x20       return Some(host);\n\
         \x20   }\n\
         \x20   let canonical = fn64_abi::recompiled::canonical_vram(vram)?;\n\
         \x20   Some(recompiled::lookup(canonical))\n}\n",
    );
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_and_underscore_names_normalize() {
        assert_eq!(adapter_name_of("osInitialize"), "os_initialize");
        assert_eq!(adapter_name_of("__ll_div"), "ll_div");
        assert_eq!(adapter_name_of("__ull_div"), "ull_div");
        assert_eq!(adapter_name_of("osAiSetNextBuffer"), "os_ai_set_next_buffer");
        assert_eq!(adapter_name_of("osCartRomInit"), "os_cart_rom_init");
        // Acronym run followed by lowercase: the EPi in osEPiStartDma.
        assert_eq!(adapter_name_of("osEPiStartDma"), "os_epi_start_dma");
        assert_eq!(adapter_name_of("osViSwapBuffer"), "os_vi_swap_buffer");
    }

    #[test]
    fn resolve_keeps_only_known_adapters_sorted_by_vram() {
        let adapters = ["os_initialize", "os_cart_rom_init", "ll_div"];
        let syms = vec![
            ("osCartRomInit".to_string(), 0x8000_5680),
            ("osInitialize".to_string(), 0x8000_3070),
            ("__ll_div".to_string(), 0x8000_227C),
            // Not an adapter -> dropped (stays recompiled).
            ("SomeGameFunc".to_string(), 0x8010_0000),
        ];
        let arms = resolve_arms(syms, &adapters);
        assert_eq!(
            arms,
            vec![
                (0x8000_227C, "ll_div".to_string()),
                (0x8000_3070, "os_initialize".to_string()),
                (0x8000_5680, "os_cart_rom_init".to_string()),
            ]
        );
    }

    #[test]
    fn render_emits_match_arms_and_the_three_fns() {
        let arms = vec![(0x8000_3070, "os_initialize".to_string())];
        let out = render(&arms);
        assert!(out.contains("0x80003070 => r::os_initialize,"));
        assert!(out.contains("fn exact_host_lookup"));
        assert!(out.contains("pub fn host_only_lookup"));
        assert!(out.contains("pub fn recompiled_or_host_lookup"));
        assert!(out.contains("use crate::recompiled"));
    }

    /// The real adapter surface must resolve OoT's core boot calls. This
    /// guards against a normalization change silently dropping an arm.
    #[test]
    fn oot_core_calls_resolve_against_real_adapter_names() {
        let adapters = fn64_abi::recompiled::adapter_names();
        for sym in [
            "osInitialize",
            "osCartRomInit",
            "osAiSetNextBuffer",
            "osViSwapBuffer",
            "osEPiStartDma",
            "__ll_div",
        ] {
            let adapter = adapter_name_of(sym);
            assert!(
                adapters.contains(&adapter.as_str()),
                "adapter `{adapter}` (from `{sym}`) not in ADAPTER_NAMES",
            );
        }
    }
}
