//! Build script: compiles OoT's out-of-tree, game-derived
//! `RecompiledFuncs/*.c` (N64Recomp's own MIT-licensed generated output)
//! plus `fn64-boot-harness`'s shared `bridge/section_bridge.c` glue into a
//! static lib the harness links against.
//!
//! Identical shape to `examples/wm2000-boot/build.rs` (that file's doc
//! comment explains the clean-room rationale in full) -- copied verbatim
//! and only the RECOMP_H_DIR hint's example path changed, since OoT's
//! bring-up (aki-recomp/games/OOTU) built directly against upstream
//! N64Recomp's own `refs/N64RecompSource/include`, not through the
//! WCWnWoRevengeRecomp vendor path WM2000 used.
//!
//! Per `fn64/README.md`'s "no game content ships in this repo" rule and
//! `fn64/AGENTS.md`'s clean-room protocol: this crate contains ZERO game
//! bytes, ZERO recompiled function bodies, and ZERO copies of
//! `recomp_overlays.inl`. Every game-derived input comes from environment
//! variables pointing OUTSIDE this repo, at build time only, never
//! vendored/copied in.
//!
//! ## Required environment variables
//!
//! - `RECOMPILED_DIR` -- path to a directory containing the N64Recomp-
//!   generated `RecompiledFuncs/*.c`, `recomp_overlays.inl`, `recomp.h`,
//!   `funcs.h` for OoT (OOTU). In the reference dev environment, this is
//!   `aki-recomp/games/OOTU/RecompiledFuncs`.
//! - `RECOMP_H_DIR` -- OPTIONAL. N64Recomp's MIT-licensed `recomp.h` (the ABI
//!   this crate serves, per `docs/DESIGN.md` section 1's provenance table) is
//!   vendored at `crates/fn64-boot-harness/bridge/include/vendor/`; set this
//!   only to build against a different fork. (`librecomp/sections.h` is
//!   fn64's OWN clean-room header and never came from N64Recomp.)
//! - `ROM` -- path to the decomp's OWN BUILD-OUTPUT ROM (NOT the retail
//!   compressed cartridge image -- OoT's linker `.map`-derived symbol rom
//!   offsets only line up against the decomp's decompressed build output;
//!   see aki-recomp/games/OOTU/docs/decomp-recomp-notes.md's "ROM basis"
//!   section for the byte-cited reason this harness hit and fixed during
//!   bring-up). In the reference dev environment, this is
//!   `aki-recomp/refs/oot-decomp/build/ntsc-1.0/oot-ntsc-1.0.z64`. Never
//!   read by this build script (only by the runtime binary, at startup) --
//!   declared here only so a missing ROM is reported early with a clear
//!   message rather than a confusing runtime panic much later.
//!
//! No default paths are baked in (they would either point outside this
//! machine or, worse, tempt a future edit to hardcode a path into a
//! colleague's home directory) -- missing/wrong env vars fail the build
//! loudly with instructions, per `AGENTS.md`'s "loud traps, no silent
//! shrugs."
//!
//! `FN64_RECOMP=rs` selects the typed-Rust lane; `c` selects the C lane and is
//! the default. In rs mode,
//! `RECOMP_RS_DIR` must contain the out-of-tree standalone crate
//! emitted by `fn64-recomp-rs`; no C file or section bridge is compiled.
//! `FN64_RS_EXECUTION` then selects `function` (the default whole-function
//! lane) or `block`. Block mode requires `RECOMP_RS_BLOCK_PROGRAM` to name one
//! out-of-tree generated Rust source file. It is included as a module and must
//! export this exact, type-checked contract:
//!
//! ```text
//! pub fn build_block_program(ProgramArtifactIdentity) -> Result<BlockProgram, String>;
//! pub fn entry() -> ExecutionKey;
//! pub fn entry_lookup(GuestPc) -> Result<ExecutionKey, CpuFault>;
//! pub fn transfer_lookup(BankId, GuestPc) -> Result<ExecutionKey, CpuFault>;
//! pub fn instruction_budget() -> InstructionBudget;
//! ```
//!
//! The builder must bind the supplied artifact identity to every
//! `GeneratedBankRunner`. The host hashes the exact source bytes, rejects an
//! empty program, verifies its entry and every runner identity, installs only
//! the host ABI lookup (never the whole-function guest fallback), and boots
//! through `boot_thread0_block_program_with_artifact_identity`. Missing or
//! malformed explicit block configuration fails the build; there is no
//! function-lane fallback. The current `recompile_rom` output does not emit
//! this file, so a discover/pack producer remains required.
//!
//! Function mode requires output regenerated by the current emitter. The
//! generated module exports `FN64_FUNCTION_ENTRY_OBSERVATION_SCHEMA`, and the
//! host hashes a path-independent wire containing an exact canonical manifest
//! plus every regular file below src/. Only the validated machine-local fn64
//! dependency path is normalized; extra targets, features, dependencies,
//! build scripts, or symlinks fail closed. That exact generated-crate identity
//! and generated schema marker make the per-function entry history admissible
//! release evidence; stale generated crates fail to compile rather than
//! silently reverting to an unobserved function lane.

use std::env;
use std::fs;
use std::path::PathBuf;

use sha2::{Digest, Sha256};

#[path = "../../crates/fn64-boot-harness/build_support.rs"]
mod build_support;

#[path = "../../crates/fn64-boot-harness/native_program_identity.rs"]
mod native_program_identity;

#[path = "block_program_config.rs"]
mod block_program_config;

#[path = "rs_program_identity.rs"]
mod rs_program_identity;

/// Locate `crates/fn64-boot-harness/bridge` by walking up from this manifest.
/// Shared by BOTH the main manifest (examples/oot-boot/) and the rs-only one
/// (examples/oot-boot/rs/, a level deeper), so a fixed `../../` breaks.
fn bridge_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let rel = "crates/fn64-boot-harness/bridge";
    let mut d = manifest_dir.as_path();
    loop {
        let candidate = d.join(rel);
        if candidate.join("section_bridge.c").exists() {
            return candidate;
        }
        match d.parent() {
            Some(p) => d = p,
            None => panic!(
                "could not locate {rel} walking up from {}",
                manifest_dir.display()
            ),
        }
    }
}

/// The vendored MIT `recomp.h`, used unless RECOMP_H_DIR overrides it.
fn vendored_recomp_h_dir() -> PathBuf {
    let d = bridge_dir().join("include/vendor");
    assert!(
        d.join("recomp.h").is_file(),
        "oot-boot build.rs: vendored recomp.h missing at {} -- it ships in this repo (MIT, \
         see LICENSE-N64Recomp beside it); set RECOMP_H_DIR to override.",
        d.display()
    );
    d
}

fn recomp_rs_runtime_dir() -> PathBuf {
    bridge_dir()
        .parent()
        .and_then(std::path::Path::parent)
        .expect("fn64 boot bridge must live below the workspace crates directory")
        .join("fn64-recomp-rs")
}

fn required_env(name: &str, hint: &str) -> PathBuf {
    match env::var(name) {
        Ok(v) => PathBuf::from(v),
        Err(_) => {
            panic!(
                "oot-boot build.rs: required environment variable {name} is not set.\n\
                 {hint}\n\
                 This example harness contains zero game content (fn64/README.md's \"no game \
                 content ships in this repo\" rule) -- every game-derived input must be supplied \
                 out-of-tree via environment variables, never vendored into this repository."
            );
        }
    }
}

fn produced_archive_bytes(out_dir: &std::path::Path, stem: &str) -> Vec<u8> {
    let candidates = [
        out_dir.join(format!("lib{stem}.a")),
        out_dir.join(format!("{stem}.lib")),
        out_dir.join(format!("lib{stem}.lib")),
    ];
    let existing: Vec<_> = candidates.iter().filter(|path| path.is_file()).collect();
    assert_eq!(
        existing.len(),
        1,
        "oot-boot build.rs: expected exactly one produced archive for {stem} in {}, found {existing:?}",
        out_dir.display()
    );
    fs::read(existing[0]).unwrap_or_else(|error| {
        panic!(
            "oot-boot build.rs: read produced native archive {}: {error}",
            existing[0].display()
        )
    })
}

fn lowercase_hex(bytes: [u8; 32]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(64);
    for byte in bytes {
        output.push(DIGITS[(byte >> 4) as usize] as char);
        output.push(DIGITS[(byte & 0x0f) as usize] as char);
    }
    output
}

fn main() {
    println!("cargo:rerun-if-env-changed=RECOMPILED_DIR");
    println!("cargo:rerun-if-env-changed=RECOMP_H_DIR");
    println!("cargo:rerun-if-env-changed=ROM");
    println!("cargo:rerun-if-env-changed=FN64_RECOMP");
    println!("cargo:rerun-if-env-changed=RECOMP_RS_DIR");
    println!("cargo:rerun-if-env-changed=FN64_RS_EXECUTION");
    println!("cargo:rerun-if-env-changed=RECOMP_RS_BLOCK_PROGRAM");
    println!("cargo:rustc-check-cfg=cfg(fn64_recomp_rs)");
    println!("cargo:rustc-check-cfg=cfg(fn64_recomp_rs_block_program)");

    let recompiled_rs = match env::var("FN64_RECOMP") {
        Ok(value) if value == "rs" => true,
        Ok(value) if value == "c" => false,
        Ok(value) => panic!("oot-boot build.rs: FN64_RECOMP must be `rs` or `c`, got {value:?}"),
        Err(env::VarError::NotPresent) => false,
        Err(env::VarError::NotUnicode(_)) => {
            panic!("oot-boot build.rs: FN64_RECOMP must be valid Unicode (`rs` or `c`)")
        }
    };

    // ROM is shared by both lanes and validated but not read here.
    let _ = required_env(
        "ROM",
        "Point it at the zeldaret/oot decomp's OWN build-output ROM (decompressed).",
    );

    let rs_execution = env::var_os("FN64_RS_EXECUTION");
    let rs_block_program = env::var_os("RECOMP_RS_BLOCK_PROGRAM");
    if !recompiled_rs && (rs_execution.is_some() || rs_block_program.is_some()) {
        panic!(
            "oot-boot build.rs: FN64_RS_EXECUTION/RECOMP_RS_BLOCK_PROGRAM configure only FN64_RECOMP=rs; refusing to ignore Rust-lane execution settings in the C lane"
        );
    }

    if recompiled_rs {
        let recompiled_dir = required_env(
            "RECOMP_RS_DIR",
            "Point it at fn64-recomp-rs's out-of-tree crate output directory.",
        );
        let manifest = recompiled_dir.join("Cargo.toml");
        let lib = recompiled_dir.join("src/lib.rs");
        assert!(
            manifest.is_file() && lib.is_file(),
            "oot-boot build.rs: RECOMP_RS_DIR={} is not an emitted recompiled function crate (expected Cargo.toml + src/lib.rs)",
            recompiled_dir.display()
        );
        let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
        let dependency_link = manifest_dir.join("recompiled");
        let selected = recompiled_dir.canonicalize().unwrap_or_else(|e| {
            panic!(
                "oot-boot build.rs: failed to canonicalize RECOMP_RS_DIR={}: {e}",
                recompiled_dir.display()
            )
        });
        let linked = dependency_link.canonicalize().unwrap_or_else(|e| {
            panic!(
                "oot-boot build.rs: rs-lane dependency link {} is unavailable: {e}; invoke examples/oot-boot/oot so it can point the path dependency at RECOMP_RS_DIR",
                dependency_link.display()
            )
        });
        assert_eq!(
            linked,
            selected,
            "oot-boot build.rs: rs-lane path dependency resolves to {}, but RECOMP_RS_DIR resolves to {}; rerun through examples/oot-boot/oot to refresh it",
            linked.display(),
            selected.display()
        );
        println!("cargo:rustc-cfg=fn64_recomp_rs");
        match block_program_config::select_rs_execution(rs_execution, rs_block_program)
            .unwrap_or_else(|error| panic!("oot-boot build.rs: {error}"))
        {
            block_program_config::RsExecution::Function => {
                let (source_wire, watched_files) =
                    rs_program_identity::canonical_source_wire(&selected, &recomp_rs_runtime_dir())
                        .unwrap_or_else(|error| {
                            panic!("oot-boot build.rs: identify generated Rust crate: {error}")
                        });
                let artifact_sha256 = lowercase_hex(Sha256::digest(&source_wire).into());
                let identity_wire_path =
                    PathBuf::from(env::var("OUT_DIR").expect("Cargo supplies OUT_DIR"))
                        .join("fn64-typed-observed-function-identity.wire");
                fs::write(&identity_wire_path, &source_wire).unwrap_or_else(|error| {
                    panic!(
                        "oot-boot build.rs: write generated-source identity wire {}: {error}",
                        identity_wire_path.display()
                    )
                });
                println!(
                    "cargo:rustc-env=FN64_RECOMP_RS_FUNCTION_ARTIFACT_SHA256={artifact_sha256}"
                );
                println!(
                    "cargo:rustc-env=FN64_RECOMP_RS_FUNCTION_IDENTITY_WIRE_PATH={}",
                    identity_wire_path.display()
                );
                for path in watched_files {
                    println!("cargo:rerun-if-changed={}", path.display());
                }
                eprintln!(
                    "oot-boot: FN64_RECOMP=rs, FN64_RS_EXECUTION=function; authoritative generated-body entry observation active (source sha256={artifact_sha256})"
                );
            }
            block_program_config::RsExecution::Block { artifact } => {
                let artifact = artifact.canonicalize().unwrap_or_else(|error| {
                    panic!(
                        "oot-boot build.rs: canonicalize block-program artifact {}: {error}",
                        artifact.display()
                    )
                });
                let bytes = fs::read(&artifact).unwrap_or_else(|error| {
                    panic!(
                        "oot-boot build.rs: read block-program artifact {}: {error}",
                        artifact.display()
                    )
                });
                assert!(
                    !bytes.is_empty(),
                    "oot-boot build.rs: RECOMP_RS_BLOCK_PROGRAM={} is empty",
                    artifact.display()
                );
                let artifact_sha256 = lowercase_hex(Sha256::digest(&bytes).into());
                println!("cargo:rustc-cfg=fn64_recomp_rs_block_program");
                println!(
                    "cargo:rustc-env=FN64_RECOMP_RS_BLOCK_PROGRAM={}",
                    artifact.display()
                );
                println!("cargo:rustc-env=FN64_RECOMP_RS_BLOCK_PROGRAM_SHA256={artifact_sha256}");
                println!("cargo:rerun-if-changed={}", artifact.display());
                eprintln!(
                    "oot-boot: FN64_RECOMP=rs, FN64_RS_EXECUTION=block; compiling exact generated pack source {} (sha256={artifact_sha256})",
                    artifact.display()
                );
            }
        }
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rerun-if-changed={}", lib.display());
        println!(
            "cargo:rerun-if-changed={}",
            recompiled_dir.join("src").display()
        );
        return;
    }

    let recompiled_dir = required_env(
        "RECOMPILED_DIR",
        "Point it at a directory containing OoT (OOTU)'s N64Recomp-generated \
         RecompiledFuncs/*.c + recomp_overlays.inl (e.g. aki-recomp/games/OOTU/RecompiledFuncs).",
    );
    // recomp.h is MIT (N64Recomp, (c) 2024 Wiseguy) and contains no game
    // content, so it is vendored at bridge/include/vendor/ -- see ROADMAP H1.
    // RECOMP_H_DIR still overrides, for testing against a different fork.
    let recomp_h_dir = env::var("RECOMP_H_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| vendored_recomp_h_dir());
    if !recompiled_dir.join("recomp_overlays.inl").exists() {
        panic!(
            "oot-boot build.rs: RECOMPILED_DIR={} does not contain recomp_overlays.inl -- \
             expected the directory N64Recomp emitted OoT's RecompiledFuncs/*.c into.",
            recompiled_dir.display()
        );
    }
    if !recomp_h_dir.join("recomp.h").exists() {
        panic!(
            "oot-boot build.rs: RECOMP_H_DIR={} does not contain recomp.h -- expected \
             N64Recomp's include/ directory.",
            recomp_h_dir.display()
        );
    }

    let bridge_dir = bridge_dir();

    let mut build = cc::Build::new();
    build
        .cpp(true)
        // The shared bridge include comes FIRST: it holds fn64's clean-room
        // stand-in librecomp/sections.h, which must shadow any real
        // (GPL-3.0-licensed) librecomp/include on the search path -- see
        // that header's doc comment and section_bridge.c's.
        .include(bridge_dir.join("include"))
        .include(&recompiled_dir)
        .include(&recomp_h_dir)
        .flag("-include")
        .flag("fn64_mmio_proxy.h")
        .flag_if_supported("-std=c++17")
        .flag_if_supported("-Wno-everything")
        // RecompiledFuncs/*.c is generated code with no warning hygiene of
        // its own (matches aki-recomp's own CMakeLists.txt build recipe for
        // this same source, per M1-WORKLIST.md's method section).
        .warnings(false);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("Cargo must provide OUT_DIR"));
    let (cxx_sources, jump_snapshot_count, prototype_count) =
        build_support::prepare_recompiled_cxx_sources(&recompiled_dir, &out_dir);
    let c_file_count = cxx_sources.len();

    build.files(cxx_sources);
    eprintln!(
        "oot-boot: compiling {c_file_count} RecompiledFuncs/*.c files from {} \
         ({jump_snapshot_count} C jump snapshots normalized and {prototype_count} missing C \
         prototypes supplied for C++)",
        recompiled_dir.display()
    );

    build.compile("oot_recompiled");

    // The bridge glue (section_bridge.c) is built SEPARATELY, as C++ --
    // recomp_overlays.inl's SectionTableEntry initializers use `nullptr`
    // (the file was generated for a C++ port build, per N64Recomp's own
    // codegen target), which is not valid in C. RecompiledFuncs/*.c also uses
    // C++ now so fn64_mmio_proxy.h can preserve MEM_W lvalue syntax while
    // intercepting raw RCP register words.
    let mut bridge_build = cc::Build::new();
    bridge_build
        .cpp(true)
        .include(bridge_dir.join("include"))
        .include(&recompiled_dir)
        .include(&recomp_h_dir)
        .flag_if_supported("-Wno-everything")
        .warnings(false)
        .file(bridge_dir.join("section_bridge.c"));
    bridge_build.compile("oot_bridge");

    // Bind the exact machine-code archives Cargo will link. The digest wire
    // contains only stable logical labels and bytes, never filesystem paths or
    // host pointers. Any compiler, archiver, build-policy, member-order, or
    // embedded-metadata difference that changes either archive intentionally
    // produces a different program identity.
    let program_identity =
        lowercase_hex(native_program_identity::native_program_archives_sha256([
            (
                "generated-code".to_owned(),
                produced_archive_bytes(&out_dir, "oot_recompiled"),
            ),
            (
                "section-bridge".to_owned(),
                produced_archive_bytes(&out_dir, "oot_bridge"),
            ),
        ]));
    println!("cargo:rustc-env=FN64_NATIVE_PROGRAM_ARTIFACT_SHA256={program_identity}");

    println!(
        "cargo:rerun-if-changed={}",
        bridge_dir.join("section_bridge.c").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        bridge_dir.join("include/fn64_mmio_proxy.h").display()
    );
    println!("cargo:rerun-if-changed={}", recompiled_dir.display());
}
