//! The typed-Rust emitter: a decoded ucode (`&[u32]` IMEM image) → a Rust
//! source string containing one `pub fn <name>(...) -> RspExitReason` that
//! runs the ucode natively against an [`crate::rsp::recomp::runtime::RspMachine`].
//!
//! ## Shape of the generated code (readable structure from RSPRecomp)
//!
//! RSPRecomp emits a straight-line C function with `goto L_XXXX` labels and a
//! `do_indirect_jump` switch. Rust has no computed `goto`, so we emit the same
//! control-flow graph as a `loop { match pc { … } }` state machine: each IMEM
//! word address is a `match` arm that runs the instruction's typed statement
//! and assigns the next `pc`. This is a faithful, type-safe transliteration of
//! RSPRecomp's `process_instruction`:
//!
//! - **Delay slots** — a branch/jump's delay-slot instruction is emitted
//!   INLINE before the control transfer (RSPRecomp duplicates the next
//!   instruction into the branch via `print_unconditional_branch` /
//!   `print_branch`). We do the same: the arm for a branch pc runs the
//!   delay-slot instruction's statement, then sets `pc` to the taken/fallthrough
//!   target.
//! - **Direct branches/jumps** — `pc = 0xTARGET;` (an absolute IMEM word addr,
//!   already masked to `0x1FFF` by the decoder).
//! - **Indirect jumps** (`jr`/`jalr`) — set `pc = jump_target & 0x1FFF` and
//!   `continue`; the `match` on `pc` IS the `do_indirect_jump` switch, and an
//!   unmatched target falls through to the `_ =>` arm returning
//!   `UnhandledJumpTarget`.
//! - **Overlay swap** — a `DO_DMA_READ` whose MEM address targets IMEM returns
//!   `RspExitReason::SwapOverlay`, matching RSPRecomp's `do_overlay_swap`.
//!   OoT's aspMain is a single always-resident overlay (no paging), so this is
//!   a trap-if-hit path, not a taken one, for that ucode.
//! - **`break`** — `return RspExitReason::Broke;` (the normal task-done exit).
//! - **Unknown instruction** — `return trap_unknown(0xADDR, 0xWORD);` — a LOUD,
//!   self-identifying trap. Never a silent skip.
//!
//! Every emitted statement calls a typed method on `RspMachine`/`VuState`
//! (`m.set_reg`, `m.vload`, `dispatch(...)`) — there is no raw pointer cast or
//! byte reinterpret in the generated text, so the emitter's output is immune
//! to the reinterpret-offset bug class.

use crate::rsp::decode::{
    decode, AluImmOp, AluRegOp, BranchOp, BranchZOp, Instr, LoadOp, ShiftOp, StoreOp, VLoadOp,
    VStoreOp,
};
use crate::rsp::ops::{operand_shape, OperandRole, VuOp};

/// Emit a complete Rust module (as a source string) for one ucode.
///
/// `words` is the IMEM text image (big-endian u32 words already byte-swapped
/// to host order by the caller). `base_vram` is the IMEM address of `words[0]`
/// masked into RSP range (aspMain's `text_address & 0x1FFF`), used to compute
/// per-instruction PCs. `fn_name` is the emitted function's name.
pub fn emit_module(words: &[u32], base_vram: u32, fn_name: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// AUTO-GENERATED by fn64-audio RSP recompiler. Do not edit.\n\
         // Source: OoT aspMain audio ucode, {} instructions, base IMEM 0x{:04X}.\n\
         #![allow(unused_variables, unused_assignments, unused_parens, unused_braces, unused_imports, clippy::all)]\n\n\
         use fn64_audio::rsp::recomp::runtime::RspMachine;\n\
         use fn64_audio::rsp::recomp::{{trap_unknown, trap_unknown_vu}};\n\
         use fn64_audio::rsp::context::RspExitReason;\n\
         use fn64_audio::rsp::ops::{{dispatch, OpInvocation, OpStatus, VuOp}};\n\n",
        words.len(),
        base_vram & 0x1FFF,
    ));

    out.push_str(&format!(
        "/// Recompiled OoT aspMain. Runs natively against `m` (the RSP machine\n\
         /// bound to rdram); returns the RSPRecomp-style exit reason.\n\
         pub fn {fn_name}(m: &mut RspMachine) -> RspExitReason {{\n"
    ));
    // r1 = 0xFC0 already set by RspMachine::new; start pc at entry.
    // A step budget converts a runaway (a branch/delay bug, or a malformed
    // command list the ucode spins on) into a LOUD, diagnosable trap that
    // names the pc it was stuck at — never a silent hang.
    out.push_str(&format!(
        "    let mut pc: u32 = 0x{:04X};\n\
         \x20   let mut steps: u64 = 0;\n\
         \x20   loop {{\n\
         \x20       steps += 1;\n\
         \x20       if steps > 5_000_000 {{ return trap_unknown(pc, 0); }}\n\
         \x20       match pc {{\n",
        base_vram & 0x1FFF
    ));

    for (i, &word) in words.iter().enumerate() {
        let pc = (base_vram & 0x1FFF) + (i as u32) * 4;
        let instr = decode(word, pc);
        let next_pc = pc + 4;
        // The delay-slot instruction (the one after a branch/jump), decoded so
        // it can be inlined into control-transfer arms.
        let delay = if i + 1 < words.len() {
            Some(decode(words[i + 1], next_pc))
        } else {
            None
        };
        out.push_str(&format!("            0x{pc:04X} => {{\n"));
        emit_instr(&mut out, &instr, pc, next_pc, delay.as_ref(), word);
        out.push_str("            }\n");
    }

    // The fallthrough / unhandled-jump-target arm (RSPRecomp's
    // do_indirect_jump default + ImemOverrun).
    out.push_str(
        "            _ => return RspExitReason::UnhandledJumpTarget,\n\
         \x20       }\n    }\n}\n",
    );
    out
}

/// Emit the body of one `match pc` arm: the instruction's typed statement,
/// then the assignment of the next `pc` (or a `return`).
fn emit_instr(
    out: &mut String,
    instr: &Instr,
    pc: u32,
    next_pc: u32,
    delay: Option<&Instr>,
    raw_word: u32,
) {
    let ind = "                ";
    match instr {
        Instr::Nop => {
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Break => {
            out.push_str(&format!("{ind}return RspExitReason::Broke;\n"));
        }
        Instr::Unknown { word } => {
            out.push_str(&format!(
                "{ind}return trap_unknown(0x{pc:04X}, 0x{word:08X});\n"
            ));
        }

        // -- straight-line ALU / loads / stores: statement then fallthrough --
        Instr::AluReg { op, rd, rs, rt } => {
            out.push_str(&format!("{ind}{}\n", alu_reg_stmt(*op, *rd, *rs, *rt)));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Shift { op, rd, rt, sa } => {
            out.push_str(&format!(
                "{ind}{}\n",
                shift_stmt(*op, *rd, *rt, *sa as u32, None)
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::ShiftVar { op, rd, rt, rs } => {
            out.push_str(&format!(
                "{ind}{}\n",
                shift_stmt(*op, *rd, *rt, 0, Some(*rs))
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::CondMove {
            on_zero,
            rd,
            rs,
            rt,
        } => {
            let cmp = if *on_zero { "==" } else { "!=" };
            out.push_str(&format!(
                "{ind}if m.reg({rt}) {cmp} 0 {{ let v = m.reg({rs}); m.set_reg({rd}, v); }}\n"
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::AluImm { op, rt, rs, imm } => {
            out.push_str(&format!("{ind}{}\n", alu_imm_stmt(*op, *rt, *rs, *imm)));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Lui { rt, imm } => {
            out.push_str(&format!(
                "{ind}m.set_reg({rt}, 0x{:08X});\n",
                (*imm as u32) << 16
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Load { op, rt, base, off } => {
            out.push_str(&format!("{ind}{}\n", load_stmt(*op, *rt, *base, *off)));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Store { op, rt, base, off } => {
            out.push_str(&format!("{ind}{}\n", store_stmt(*op, *rt, *base, *off)));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }

        // -- CP2 transfers --
        Instr::Mfc0 { rt, cop0 } => {
            // mfc0 reads RSP status/DMA regs; all "instant/idle" per RSPRecomp
            // expected_c0_reg_value -> 0. We model them as 0.
            out.push_str(&format!("{ind}m.set_reg({rt}, 0);\n"));
            let _ = cop0;
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Mtc0 { rt, cop0 } => {
            emit_mtc0(out, ind, *rt, *cop0, pc, next_pc, false);
        }
        Instr::Mfc2 { rt, vs, elem } => {
            out.push_str(&format!(
                "{ind}let v = m.mfc2({vs}, {elem}); m.set_reg({rt}, v);\n"
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Mtc2 { rt, vs, elem } => {
            out.push_str(&format!(
                "{ind}let v = m.reg({rt}); m.mtc2({vs}, {elem}, v);\n"
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Cfc2 { rt, cd } => {
            out.push_str(&format!("{ind}let v = m.cfc2({cd}); m.set_reg({rt}, v);\n"));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::Ctc2 { rt, cd } => {
            out.push_str(&format!("{ind}let v = m.reg({rt}); m.ctc2({cd}, v);\n"));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::VLoad {
            op,
            vt,
            elem,
            base,
            off,
        } => {
            out.push_str(&format!(
                "{ind}let b = m.reg({base}); m.vload({}, {vt}, {elem}, b, {off});\n",
                vload_variant(*op)
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        Instr::VStore {
            op,
            vt,
            elem,
            base,
            off,
        } => {
            out.push_str(&format!(
                "{ind}let b = m.reg({base}); m.vstore({}, {vt}, {elem}, b, {off});\n",
                vstore_variant(*op)
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }

        // -- CP2 compute --
        Instr::Vu {
            op,
            vd,
            vs,
            vt,
            e,
            de,
        } => {
            out.push_str(&vu_stmt(ind, pc, *op, *vd, *vs, *vt, *e, *de));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }

        // -- control transfers (delay slot inlined) --
        Instr::Branch { op, rs, rt, target } => {
            let cond = match op {
                BranchOp::Beq => format!("m.reg({rs}) == m.reg({rt})"),
                BranchOp::Bne => format!("m.reg({rs}) != m.reg({rt})"),
            };
            emit_conditional_branch(out, ind, &cond, *target, next_pc, delay);
        }
        Instr::BranchZ { op, rs, target } => {
            let cond = match op {
                BranchZOp::Blez => format!("(m.reg({rs}) as i32) <= 0"),
                BranchZOp::Bgtz => format!("(m.reg({rs}) as i32) > 0"),
                BranchZOp::Bltz => format!("(m.reg({rs}) as i32) < 0"),
                BranchZOp::Bgez => format!("(m.reg({rs}) as i32) >= 0"),
            };
            emit_conditional_branch(out, ind, &cond, *target, next_pc, delay);
        }
        Instr::Jump { target } => {
            emit_delay(out, ind, delay);
            out.push_str(&format!("{ind}pc = 0x{target:04X};\n"));
        }
        Instr::Jal { target, ret } => {
            out.push_str(&format!("{ind}m.set_reg(31, 0x{ret:04X});\n"));
            emit_delay(out, ind, delay);
            out.push_str(&format!("{ind}pc = 0x{target:04X};\n"));
        }
        Instr::Jr { rs } => {
            out.push_str(&format!("{ind}let jt = m.reg({rs}) & 0x1FFF;\n"));
            emit_delay(out, ind, delay);
            out.push_str(&format!("{ind}pc = jt;\n"));
        }
        Instr::Jalr { rd, rs, ret } => {
            out.push_str(&format!(
                "{ind}let jt = m.reg({rs}) & 0x1FFF; m.set_reg({rd}, 0x{ret:04X});\n"
            ));
            emit_delay(out, ind, delay);
            out.push_str(&format!("{ind}pc = jt;\n"));
        }
    }
    let _ = raw_word;
}

/// Emit a conditional branch: `if cond { <delay> pc = target } else { <delay> pc = next }`.
/// The delay-slot instruction runs on BOTH paths (MIPS delay-slot semantics),
/// matching RSPRecomp duplicating it into taken and fallthrough.
fn emit_conditional_branch(
    out: &mut String,
    ind: &str,
    cond: &str,
    target: u16,
    next_pc: u32,
    delay: Option<&Instr>,
) {
    out.push_str(&format!("{ind}if {cond} {{\n"));
    emit_delay(out, ind, delay);
    out.push_str(&format!("{ind}    pc = 0x{target:04X};\n{ind}}} else {{\n"));
    emit_delay(out, ind, delay);
    out.push_str(&format!("{ind}    pc = 0x{next_pc:04X};\n{ind}}}\n"));
}

/// Emit ONLY the side-effecting statement of a delay-slot instruction (no
/// pc assignment — the branch owns pc). A nop delay slot emits nothing.
fn emit_delay(out: &mut String, ind: &str, delay: Option<&Instr>) {
    let Some(d) = delay else { return };
    let stmt = delay_stmt(d);
    if let Some(s) = stmt {
        out.push_str(&format!("{ind}    {s}\n"));
    }
}

/// The pure side-effect statement for an instruction placed in a delay slot.
/// Delay slots in well-formed ucode never contain a second branch/jump, so we
/// only handle the value-producing ops here; a branch-in-delay-slot returns
/// `None` and the emitter's `Unknown`/trap path would have caught truly odd
/// encodings at the primary arm.
fn delay_stmt(d: &Instr) -> Option<String> {
    Some(match d {
        Instr::Nop => return None,
        Instr::AluReg { op, rd, rs, rt } => alu_reg_stmt(*op, *rd, *rs, *rt),
        Instr::Shift { op, rd, rt, sa } => shift_stmt(*op, *rd, *rt, *sa as u32, None),
        Instr::ShiftVar { op, rd, rt, rs } => shift_stmt(*op, *rd, *rt, 0, Some(*rs)),
        Instr::CondMove {
            on_zero,
            rd,
            rs,
            rt,
        } => {
            let cmp = if *on_zero { "==" } else { "!=" };
            format!("if m.reg({rt}) {cmp} 0 {{ let v = m.reg({rs}); m.set_reg({rd}, v); }}")
        }
        Instr::AluImm { op, rt, rs, imm } => alu_imm_stmt(*op, *rt, *rs, *imm),
        Instr::Lui { rt, imm } => format!("m.set_reg({rt}, 0x{:08X});", (*imm as u32) << 16),
        Instr::Load { op, rt, base, off } => load_stmt(*op, *rt, *base, *off),
        Instr::Store { op, rt, base, off } => store_stmt(*op, *rt, *base, *off),
        Instr::Mfc0 { rt, .. } => format!("m.set_reg({rt}, 0);"),
        Instr::Mfc2 { rt, vs, elem } => {
            format!("{{ let v = m.mfc2({vs}, {elem}); m.set_reg({rt}, v); }}")
        }
        Instr::Mtc2 { rt, vs, elem } => {
            format!("{{ let v = m.reg({rt}); m.mtc2({vs}, {elem}, v); }}")
        }
        Instr::Cfc2 { rt, cd } => format!("{{ let v = m.cfc2({cd}); m.set_reg({rt}, v); }}"),
        Instr::Ctc2 { rt, cd } => format!("{{ let v = m.reg({rt}); m.ctc2({cd}, v); }}"),
        Instr::VLoad {
            op,
            vt,
            elem,
            base,
            off,
        } => format!(
            "{{ let b = m.reg({base}); m.vload({}, {vt}, {elem}, b, {off}); }}",
            vload_variant(*op)
        ),
        Instr::VStore {
            op,
            vt,
            elem,
            base,
            off,
        } => format!(
            "{{ let b = m.reg({base}); m.vstore({}, {vt}, {elem}, b, {off}); }}",
            vstore_variant(*op)
        ),
        Instr::Vu {
            op,
            vd,
            vs,
            vt,
            e,
            de,
        } => {
            // Wrap the (already multi-line) vu statement in a block.
            format!(
                "{{ {} }}",
                vu_stmt("", 0, *op, *vd, *vs, *vt, *e, *de).replace('\n', " ")
            )
        }
        // mtc0 in a delay slot: emit its DMA effect but not the overlay-swap
        // early return (a swap-triggering DMA in a delay slot is handled at the
        // primary arm; audio ucode DMAs are not in delay slots).
        Instr::Mtc0 { rt, cop0 } => mtc0_effect(*rt, *cop0),
        // A branch/jump/break/unknown in a delay slot is not well-formed here.
        _ => return None,
    })
}

// --- statement builders (each returns ONE typed Rust statement) ---

fn alu_reg_stmt(op: AluRegOp, rd: u8, rs: u8, rt: u8) -> String {
    let expr = match op {
        AluRegOp::Add | AluRegOp::Addu => {
            format!("m.reg({rs}).wrapping_add(m.reg({rt}))")
        }
        AluRegOp::Sub | AluRegOp::Subu => {
            format!("m.reg({rs}).wrapping_sub(m.reg({rt}))")
        }
        AluRegOp::And => format!("m.reg({rs}) & m.reg({rt})"),
        AluRegOp::Or => format!("m.reg({rs}) | m.reg({rt})"),
        AluRegOp::Xor => format!("m.reg({rs}) ^ m.reg({rt})"),
        AluRegOp::Nor => format!("!(m.reg({rs}) | m.reg({rt}))"),
        AluRegOp::Slt => {
            format!("if (m.reg({rs}) as i32) < (m.reg({rt}) as i32) {{ 1 }} else {{ 0 }}")
        }
        AluRegOp::Sltu => format!("if m.reg({rs}) < m.reg({rt}) {{ 1 }} else {{ 0 }}"),
    };
    format!("let v = {expr}; m.set_reg({rd}, v);")
}

fn shift_stmt(op: ShiftOp, rd: u8, rt: u8, sa: u32, rs: Option<u8>) -> String {
    let amt = match rs {
        Some(r) => format!("(m.reg({r}) & 31)"),
        None => format!("{sa}"),
    };
    let expr = match op {
        ShiftOp::Sll => format!("m.reg({rt}) << {amt}"),
        ShiftOp::Srl => format!("m.reg({rt}) >> {amt}"),
        ShiftOp::Sra => format!("((m.reg({rt}) as i32) >> {amt}) as u32"),
    };
    format!("let v = {expr}; m.set_reg({rd}, v);")
}

fn alu_imm_stmt(op: AluImmOp, rt: u8, rs: u8, imm: u16) -> String {
    let simm = imm as i16 as i32 as u32;
    let expr = match op {
        AluImmOp::Addi | AluImmOp::Addiu => {
            format!("m.reg({rs}).wrapping_add(0x{simm:08X})")
        }
        AluImmOp::Slti => {
            format!(
                "if (m.reg({rs}) as i32) < ({} as i32) {{ 1 }} else {{ 0 }}",
                imm as i16 as i32
            )
        }
        AluImmOp::Sltiu => format!("if m.reg({rs}) < 0x{simm:08X} {{ 1 }} else {{ 0 }}"),
        AluImmOp::Andi => format!("m.reg({rs}) & 0x{:X}", imm as u32),
        AluImmOp::Ori => format!("m.reg({rs}) | 0x{:X}", imm as u32),
        AluImmOp::Xori => format!("m.reg({rs}) ^ 0x{:X}", imm as u32),
    };
    format!("let v = {expr}; m.set_reg({rt}, v);")
}

fn load_stmt(op: LoadOp, rt: u8, base: u8, off: i16) -> String {
    let addr = format!("m.reg({base}).wrapping_add(0x{:08X})", off as i32 as u32);
    let call = match op {
        LoadOp::Lb => "load_b",
        LoadOp::Lbu => "load_bu",
        LoadOp::Lh => "load_h",
        LoadOp::Lhu => "load_hu",
        LoadOp::Lw => "load_w",
    };
    format!("let a = {addr}; let v = m.{call}(a); m.set_reg({rt}, v);")
}

fn store_stmt(op: StoreOp, rt: u8, base: u8, off: i16) -> String {
    let addr = format!("m.reg({base}).wrapping_add(0x{:08X})", off as i32 as u32);
    let call = match op {
        StoreOp::Sb => "store_b",
        StoreOp::Sh => "store_h",
        StoreOp::Sw => "store_w",
    };
    format!("let a = {addr}; let v = m.reg({rt}); m.{call}(a, v);")
}

fn vload_variant(op: VLoadOp) -> &'static str {
    use fn64_vload_names::*;
    match op {
        VLoadOp::Lbv => LBV,
        VLoadOp::Lsv => LSV,
        VLoadOp::Llv => LLV,
        VLoadOp::Ldv => LDV,
        VLoadOp::Lqv => LQV,
        VLoadOp::Lrv => LRV,
        VLoadOp::Lpv => LPV,
        VLoadOp::Luv => LUV,
        VLoadOp::Lhv => LHV,
        VLoadOp::Lfv => LFV,
        VLoadOp::Ltv => LTV,
    }
}

fn vstore_variant(op: VStoreOp) -> &'static str {
    match op {
        VStoreOp::Sbv => "fn64_audio::rsp::decode::VStoreOp::Sbv",
        VStoreOp::Ssv => "fn64_audio::rsp::decode::VStoreOp::Ssv",
        VStoreOp::Slv => "fn64_audio::rsp::decode::VStoreOp::Slv",
        VStoreOp::Sdv => "fn64_audio::rsp::decode::VStoreOp::Sdv",
        VStoreOp::Sqv => "fn64_audio::rsp::decode::VStoreOp::Sqv",
        VStoreOp::Srv => "fn64_audio::rsp::decode::VStoreOp::Srv",
        VStoreOp::Spv => "fn64_audio::rsp::decode::VStoreOp::Spv",
        VStoreOp::Suv => "fn64_audio::rsp::decode::VStoreOp::Suv",
        VStoreOp::Shv => "fn64_audio::rsp::decode::VStoreOp::Shv",
        VStoreOp::Sfv => "fn64_audio::rsp::decode::VStoreOp::Sfv",
        VStoreOp::Swv => "fn64_audio::rsp::decode::VStoreOp::Swv",
        VStoreOp::Stv => "fn64_audio::rsp::decode::VStoreOp::Stv",
    }
}

mod fn64_vload_names {
    pub const LBV: &str = "fn64_audio::rsp::decode::VLoadOp::Lbv";
    pub const LSV: &str = "fn64_audio::rsp::decode::VLoadOp::Lsv";
    pub const LLV: &str = "fn64_audio::rsp::decode::VLoadOp::Llv";
    pub const LDV: &str = "fn64_audio::rsp::decode::VLoadOp::Ldv";
    pub const LQV: &str = "fn64_audio::rsp::decode::VLoadOp::Lqv";
    pub const LRV: &str = "fn64_audio::rsp::decode::VLoadOp::Lrv";
    pub const LPV: &str = "fn64_audio::rsp::decode::VLoadOp::Lpv";
    pub const LUV: &str = "fn64_audio::rsp::decode::VLoadOp::Luv";
    pub const LHV: &str = "fn64_audio::rsp::decode::VLoadOp::Lhv";
    pub const LFV: &str = "fn64_audio::rsp::decode::VLoadOp::Lfv";
    pub const LTV: &str = "fn64_audio::rsp::decode::VLoadOp::Ltv";
}

/// Emit a CP2 compute op as a typed `dispatch(...)` call building an
/// `OpInvocation` from the op's operand shape. The generated code traps loudly
/// (via `OpStatus::Unimplemented`) if a not-yet-wired op is reached.
fn vu_stmt(ind: &str, pc: u32, op: VuOp, vd: u8, vs: u8, vt: u8, e: u8, de: u8) -> String {
    let _shape = operand_shape(op); // presence check / documentation
    let _ = OperandRole::VsIndex;
    let variant = vu_variant(op);
    // Build an OpInvocation carrying every field; the op body reads only those
    // its shape declares (vs_index mirrors vs for VRNDN/VRNDP).
    let inv = format!(
        "OpInvocation {{ vd: {vd}, vs: {vs}, vt: {vt}, e: {e}, de: {de}, vs_index: {vs} }}"
    );
    format!(
        "{ind}match dispatch(m.vu(), {variant}, {inv}) {{\n\
         {ind}    OpStatus::Executed => {{}}\n\
         {ind}    OpStatus::Unimplemented(op) => return trap_unknown_vu(0x{pc:04X}, op),\n\
         {ind}}}\n"
    )
}

fn vu_variant(op: VuOp) -> String {
    format!("VuOp::{op:?}")
}

/// Emit an `mtc0` (CP2 DMA / status register write). This is the ONE place the
/// overlay-swap early return can be emitted (a `DO_DMA_READ` into IMEM).
fn emit_mtc0(out: &mut String, ind: &str, rt: u8, cop0: u8, pc: u32, next_pc: u32, _delay: bool) {
    // RSP CP0 register indices (n64brew "RSP Registers"):
    //  0 SP_MEM_ADDR, 1 SP_DRAM_ADDR, 2 SP_RD_LEN, 3 SP_WR_LEN, 4 SP_STATUS,
    //  5 SP_DMA_FULL, 6 SP_DMA_BUSY, 7 SP_SEMAPHORE.
    match cop0 {
        0 => {
            out.push_str(&format!("{ind}let v = m.reg({rt}); m.set_dma_mem(v);\n"));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        1 => {
            out.push_str(&format!("{ind}let v = m.reg({rt}); m.set_dma_dram(v);\n"));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        2 => {
            // DO_DMA_READ: may trigger an overlay swap.
            out.push_str(&format!(
                "{ind}let v = m.reg({rt});\n\
                 {ind}if let Some(r) = m.dma_read(v) {{ m.ctx.resume_address = 0x{pc:04X}; return r; }}\n"
            ));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        3 => {
            out.push_str(&format!("{ind}let v = m.reg({rt}); m.dma_write(v);\n"));
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
        // status / semaphore writes: ignored (RSPRecomp c0_reg_write_action
        // returns "" for these — yielding/semaphore are no-ops in recomp).
        _ => {
            out.push_str(&format!("{ind}pc = 0x{next_pc:04X};\n"));
        }
    }
}

/// The delay-slot form of an mtc0 (DMA effect only, no overlay-swap return).
fn mtc0_effect(rt: u8, cop0: u8) -> String {
    match cop0 {
        0 => format!("{{ let v = m.reg({rt}); m.set_dma_mem(v); }}"),
        1 => format!("{{ let v = m.reg({rt}); m.set_dma_dram(v); }}"),
        2 => format!("{{ let v = m.reg({rt}); let _ = m.dma_read(v); }}"),
        3 => format!("{{ let v = m.reg({rt}); m.dma_write(v); }}"),
        _ => "{}".to_string(),
    }
}
