//! Copies the generated, game-derived aspMain module into `OUT_DIR`.
//!
//! Locating it: `OOT_ASPMAIN` (a full path to the file) wins; otherwise
//! `$FN64_GAME_DIR/games/OOTU/rsp-recomp/src/oot_aspmain.rs`. There is NO
//! relative-path fallback, deliberately: a relative guess silently assumes the
//! game workspace sits at a fixed offset from this manifest, which is false in
//! any git worktree and for any contributor. Ask for a path; never guess one.
//!
//! The module is ROM-derived (recompiled aspMain ucode), so unlike `recomp.h`
//! it can never be vendored -- it must stay out-of-tree per the
//! no-game-content rule. This optional translated-artifact experiment is not
//! linked by the parent harness, which executes admitted live IMEM via LLE.

use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-env-changed=OOT_ASPMAIN");
    println!("cargo:rerun-if-env-changed=FN64_GAME_DIR");

    let generated = locate();
    let out = PathBuf::from(std::env::var_os("OUT_DIR").unwrap()).join("oot_aspmain.rs");
    let source = std::fs::read_to_string(&generated)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", generated.display()));
    // The emitter writes a crate-level `#![allow(...)]`. This adapter includes
    // the generated file as a module, where an inner attribute is invalid; the
    // adapter crate carries the identical allow at its own root instead.
    let source = source
        .lines()
        .filter(|line| !line.starts_with("#![allow("))
        .collect::<Vec<_>>()
        .join("\n");
    assert_not_stale_delay_slot_codegen(&source, &generated);
    std::fs::write(&out, source)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", out.display()));
    println!("cargo:rerun-if-changed={}", generated.display());
}

fn assert_not_stale_delay_slot_codegen(source: &str, generated: &std::path::Path) {
    let stale_oot_aspmain = "0x11D8 => {\n                if (m.reg(1) as i32) > 0 {\n                    { let b = m.reg(4); m.vstore(fn64_audio::rsp::decode::VStoreOp::Ssv, 2, 6, b, -1); }\n                    pc = 0x11A4;\n                } else {\n                    { let b = m.reg(4); m.vstore(fn64_audio::rsp::decode::VStoreOp::Ssv, 2, 6, b, -1); }\n                    pc = 0x11DC;\n                }\n            }\n            0x11DC => {\n                let b = m.reg(4); m.vstore(fn64_audio::rsp::decode::VStoreOp::Ssv, 2, 6, b, -1);";
    assert!(
        !source.contains(stale_oot_aspmain),
        "OoT audio adapter: {} was generated by stale RSP branch-delay codegen. \
         The not-taken branch at 0x11D8 resumes at its delay slot (0x11DC), \
         executing SSV twice and corrupting PCM. Regenerate oot_aspmain.rs with \
         the current fn64-audio rsp_recompile emitter, or set OOT_ASPMAIN to a \
         freshly emitted module.",
        generated.display()
    );
}

/// Resolve the generated module, or panic naming every place we looked and how
/// to proceed. A loud, actionable trap -- never a silent stand-in, which would
/// mean shipping the synth while claiming real audio (AGENTS.md: no silent
/// shrugs, and R5 is an open audio bug where that lie would be expensive).
fn locate() -> PathBuf {
    const REL: &str = "games/OOTU/rsp-recomp/src/oot_aspmain.rs";

    if let Some(explicit) = std::env::var_os("OOT_ASPMAIN") {
        let p = PathBuf::from(explicit);
        assert!(
            p.is_file(),
            "OoT audio adapter: OOT_ASPMAIN={} is not a file.",
            p.display()
        );
        return p;
    }

    // FN64_GAME_DIR: the workspace holding a user's own ROM-derived material.
    if let Some(dir) = std::env::var_os("FN64_GAME_DIR") {
        let p = PathBuf::from(dir).join(REL);
        if p.is_file() {
            return p;
        }
        panic!(
            "OoT audio adapter: FN64_GAME_DIR is set but {} does not exist.\n\
             Set OOT_ASPMAIN to the generated module's full path.",
            p.display()
        );
    }

    panic!(
        "OoT audio adapter: cannot locate the generated aspMain module.\n\
         It is ROM-derived, so it never ships in this repo (see the vendor README for \
         what CAN be vendored).\n\
         Set one of:\n\
         \x20 OOT_ASPMAIN=/path/to/oot_aspmain.rs   (the file itself)\n\
         \x20 FN64_GAME_DIR=/path/to/game-workspace (then {REL})"
    );
}
