#!/usr/bin/env python3
"""
import_decomp_map.py — translate a zeldaret-style decomp's REAL build output
(linker .map) into the answer-key dump.toml shape fn64-discover's reference
adapter ingests. Generalized from aki-recomp's games/OOTU/tools/
import_oot_syms.py (same extraction rules, minus the aki-profile outputs) so
one importer serves every map-based decomp: OoT (ntsc-1.0) and Majora's Mask
(n64-us) share this build infrastructure.

WHY A .map: map-based decomps have no static symbol_addrs.txt — function
VRAM addresses only exist as a build output. The input is the decomp
checkout's OWN BUILD ARTIFACT after building it against the user's own ROM
(e.g. `make setup VERSION=n64-us && make VERSION=n64-us` in zeldaret/mm).
The output is decomp METADATA only (names, addresses, sizes) with cited
provenance — no ROM bytes, per the repo's no-ROM-bytes rule. Splat-based
decomps use scripts/import_splat_syms.py instead; both emit the same
dump.toml.

Usage:
    <decomp>/.venv/bin/python3 scripts/import_decomp_map.py \
        --map <decomp>/build/n64-us/mm-n64-us.map \
        --game "Majora's Mask (N64 US 1.0)" \
        --decomp-url https://github.com/zeldaret/mm \
        --rom-sha1 <sha1 of the matching retail ROM> \
        --out games/MM/syms/dump.toml

Requires `mapfile_parser` (installed by such decomps' own setup step) — run
with the decomp venv's python3, not system python3.

Verification recipe (differential, no new ground truth): run against the
zeldaret/oot ntsc-1.0 build map and diff the [[section]] content against
aki-recomp's games/OOTU/syms/dump.toml — the two importers must agree.
"""

import argparse
import sys
from pathlib import Path

try:
    import mapfile_parser
except ImportError:
    print(
        "ERROR: mapfile_parser not importable. Run this script with the "
        "decomp checkout's .venv/bin/python3, not system python3.",
        file=sys.stderr,
    )
    sys.exit(1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--map", required=True, type=Path, help="decomp build .map")
    ap.add_argument("--out", required=True, type=Path, help="output dump.toml path")
    ap.add_argument("--game", required=True, help='display name, e.g. "Majora\'s Mask (N64 US 1.0)"')
    ap.add_argument("--decomp-url", required=True, help="decomp repo URL for the provenance banner")
    ap.add_argument("--rom-sha1", required=True, help="sha1 of the ROM this build matches")
    args = ap.parse_args()

    print(f"Loading map file: {args.map}", file=sys.stderr)
    mf = mapfile_parser.mapfile.MapFile()
    mf.readMapFile(str(args.map))
    print(f"  {len(mf)} linker segments", file=sys.stderr)

    sections_out = []
    total_funcs = 0
    named_funcs = 0

    for seg in mf:
        # Strip the linker's leading ".." decoration (e.g. "..ovl_En_Test").
        clean_name = seg.name[2:] if seg.name.startswith("..") else seg.name
        # dump.toml [[section]] names feed identifier-shaped consumers (see
        # the OOTU importer's N64Recomp note): '.' would produce invalid
        # identifiers downstream.
        dump_toml_name = clean_name.replace(".", "_")

        for sec in seg:
            if sec.sectionType != ".text" or sec.vram is None:
                continue
            funcs = []
            for sym in sec:
                # mapfile_parser synthesizes "$_static_symbol_..." names for
                # unlabeled .text (raw header bytes at vram 0x0, not real
                # cartridge-mapped code); skip those and anything outside
                # KSEG0 rather than mis-counting them as functions.
                if sym.vram is None or sym.vram < 0x8000_0000:
                    continue
                if sym.name.startswith("$_static_symbol_"):
                    continue
                total_funcs += 1
                if not sym.name.startswith("func_"):
                    named_funcs += 1
                funcs.append(
                    {"name": sym.name, "vram": sym.vram, "size": sym.size or 0}
                )
            if not funcs:
                continue
            sections_out.append(
                {
                    "name": dump_toml_name,
                    "rom": sec.vrom if sec.vrom is not None else 0,
                    "vram": sec.vram,
                    "size": sec.size,
                    "functions": funcs,
                }
            )

    if not sections_out:
        print("ERROR: no function-bearing .text sections found in map", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as f:
        f.write(
            f"# Autogenerated by scripts/import_decomp_map.py from the {args.game}\n"
            f"# decomp's OWN BUILD OUTPUT ({args.decomp_url},\n"
            f"# built from source against ROM sha1 {args.rom_sha1}). Real function\n"
            "# names come directly from that decomp's source; func_XXXXXXXX\n"
            "# entries are functions the decomp itself has not yet named (honest\n"
            "# upstream gap, not ours). DO NOT hand-edit — rerun the importer\n"
            "# against a fresh .map instead.\n"
            "#\n"
            f"# Sections: {len(sections_out)}   Functions: {total_funcs}   "
            f"Real-named: {named_funcs}   Unnamed (func_*): {total_funcs - named_funcs}\n\n"
        )
        for sec in sections_out:
            f.write("[[section]]\n")
            f.write(f'name = "{sec["name"]}"\n')
            f.write(f'rom = 0x{sec["rom"]:08x}\n')
            f.write(f'vram = 0x{sec["vram"]:08x}\n')
            f.write(f'size = 0x{sec["size"]:x}\n\n')
            f.write("functions = [\n")
            for fn in sec["functions"]:
                f.write(
                    f'    {{ name = "{fn["name"]}", vram = 0x{fn["vram"]:08x}, '
                    f'size = 0x{fn["size"]:x} }},\n'
                )
            f.write("]\n\n")

    print(f"Wrote {args.out}", file=sys.stderr)
    print("\n=== Import summary ===")
    print(f"Sections (.text): {len(sections_out)}")
    print(f"Total functions: {total_funcs}")
    print(f"Real-named functions: {named_funcs}")
    print(f"Unnamed func_XXXXXXXX: {total_funcs - named_funcs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
