#!/usr/bin/env python3
"""Every `unsafe` site in a hand-written crate source must justify itself.

# The rule

An `unsafe {` block or an `unsafe fn` declaration must carry a `// SAFETY:`
comment within the three lines preceding it, or -- for an `unsafe fn`, whose
obligation is on its *callers* -- a `# Safety` section in its rustdoc. Anything
else is an unsafe site whose invariant lives only in the author's head, which
is the failure mode AGENTS.md's "types before audits" rule names: an invariant
enforced by review is a bug with a delay timer.

The three-line window is deliberate. A `// SAFETY:` comment must sit adjacent
to the operation it justifies; one that has drifted a screen away from its
block has stopped being a claim about that block. Three lines allows a short
wrapped comment plus an attribute line, and nothing more.

# Warn mode (current)

This lint currently runs in WARN mode: it reports the count and every
unjustified site, and exits 0. Task 4.7 introduced it against a real backlog
(measured at introduction: 1,200 sites across the workspace, 200 of them
already justified), and a lint that fails on day one against a four-figure
backlog is a lint everyone learns to skip. It runs in CI so the number is
visible on every build and cannot quietly grow unnoticed.

Pass `--fail` to exit non-zero on any finding; pass `--max <n>` to fail only
if the count EXCEEDS `n`, which is how this becomes a ratchet before it
becomes a wall. Task 4.7 Step 3 flips the default once the count reaches zero.

# Scope

Hand-written library and test sources under `crates/*/src`. Generated sources
are excluded by content marker, not by a hand-maintained path list: a file
whose head declares itself generated is not a file anyone can add a comment
to, and a path allowlist would go stale the moment a generator's output moved.
This follows `lint-hot-path-env.py`'s convention of making the rule a property
of the tree rather than of a registry someone has to remember to update.

Run with `--self-test` to exercise the checker against synthetic sources,
including a planted unjustified block that must be reported.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]

# How many lines above a site a `// SAFETY:` comment may sit and still count
# as adjacent to it.
SAFETY_WINDOW = 3

# An `unsafe {` block, or an `unsafe fn` declaration (including
# `pub unsafe extern "C" fn`). `unsafe impl` and `unsafe trait` are NOT sites:
# their obligation is discharged by the impl as a whole, and rustc already
# requires the author to write `unsafe` there deliberately.
# The ABI string in `extern "C"` has been blanked to spaces by
# `strip_strings_and_comments` before this runs, so the ABI clause is matched
# as `extern` followed by whitespace rather than by a quoted name.
SITE = re.compile(r'(?P<block>\bunsafe\s*\{)|(?P<fn>\bunsafe\s+(?:extern\s+)?fn\b)')

SAFETY_COMMENT = re.compile(r'^\s*(?://+|/\*+|\*)\s*SAFETY\b', re.IGNORECASE)

# A rustdoc `# Safety` section anywhere in the doc comment block immediately
# above an `unsafe fn`. An `unsafe fn`'s contract is owed to its callers, and
# rustdoc is where callers read it -- `clippy::missing_safety_doc` uses the
# same rule.
SAFETY_DOC = re.compile(r'^\s*///+\s*#+\s*Safety\b', re.IGNORECASE)
DOC_LINE = re.compile(r'^\s*(?:///|//!|#\[|#!\[)')

# A file whose first lines say a generator wrote it. Matched against the head
# of the file only, so a source that merely mentions the phrase in prose deep
# in a doc comment is not excused.
GENERATED_MARKER = re.compile(
    r'@generated|GENERATED FILE|DO NOT EDIT|Generated by|generated by '
    r'|auto-generated|autogenerated',
    re.IGNORECASE,
)
GENERATED_HEAD_LINES = 15


def is_generated(source: str) -> bool:
    """True if the file's head declares it machine-written."""
    head = "\n".join(source.split("\n")[:GENERATED_HEAD_LINES])
    return bool(GENERATED_MARKER.search(head))


def strip_strings_and_comments(source: str) -> str:
    """Blank out string/char literals and comments, preserving line structure.

    Without this, a `"unsafe {"` inside a codegen template or a test's
    expected-output literal counts as a site -- and `fn64-cpu-runtime-codegen`
    emits exactly such strings; a commented-out `unsafe { .. }` would count
    too. Newlines are preserved so line numbers computed against the result
    still address the original file.

    String CONTENT is blanked but the delimiters are kept as spaces, which
    would break `unsafe extern "C" fn` -- the `"C"` is a string literal. The
    ABI string is therefore restored below, since an `extern` ABI name is part
    of a declaration's syntax, not data.
    """
    out = []
    i = 0
    n = len(source)
    while i < n:
        c = source[i]
        if c == '"':
            # Raw string: r"..", r#".."#, r##".."##
            hashes = 0
            j = i - 1
            while j >= 0 and source[j] == '#':
                hashes += 1
                j -= 1
            is_raw = j >= 0 and source[j] == 'r'
            out.append(' ')
            i += 1
            if is_raw:
                terminator = '"' + '#' * hashes
                end = source.find(terminator, i)
                end = n if end < 0 else end
                out.append(re.sub(r'[^\n]', ' ', source[i:end]))
                i = end
            else:
                while i < n and source[i] != '"':
                    if source[i] == '\\':
                        out.append(' ')
                        i += 1
                        if i < n:
                            out.append('\n' if source[i] == '\n' else ' ')
                            i += 1
                        continue
                    out.append('\n' if source[i] == '\n' else ' ')
                    i += 1
            if i < n:
                out.append(' ')
                i += 1
            continue
        if c == '/' and i + 1 < n and source[i + 1] == '/':
            # Blanked, not kept: a commented-out `unsafe { .. }` is not a site.
            # SAFETY comments are found by scanning the ORIGINAL lines in
            # `justified`, so blanking here costs nothing.
            while i < n and source[i] != '\n':
                out.append(' ')
                i += 1
            continue
        if c == '/' and i + 1 < n and source[i + 1] == '*':
            depth = 1
            out.append('  ')
            i += 2
            while i < n and depth:
                if source.startswith('/*', i):
                    depth += 1
                    out.append('  ')
                    i += 2
                elif source.startswith('*/', i):
                    depth -= 1
                    out.append('  ')
                    i += 2
                else:
                    out.append('\n' if source[i] == '\n' else ' ')
                    i += 1
            continue
        if c == "'":
            # A char literal, or a lifetime. Only a literal needs blanking.
            m = re.match(r"'(?:\\.|[^\\'])'", source[i:])
            if m:
                out.append(' ' * len(m.group(0)))
                i += len(m.group(0))
                continue
        out.append(c)
        i += 1
    return "".join(out)


def justified(lines: list[str], line_index: int, is_fn: bool) -> bool:
    """Whether the site at `line_index` (0-based) carries its justification."""
    start = max(0, line_index - SAFETY_WINDOW)
    for probe in lines[start:line_index]:
        if SAFETY_COMMENT.search(probe):
            return True
    if not is_fn:
        return False
    # An `unsafe fn`: accept a `# Safety` rustdoc section in the doc block
    # immediately above it, however long that block is.
    probe = line_index - 1
    while probe >= 0 and DOC_LINE.match(lines[probe]):
        if SAFETY_DOC.match(lines[probe]):
            return True
        probe -= 1
    return False


def check_source(relative: str, source: str) -> list[str]:
    """Every unjustified unsafe site in one file, as formatted findings."""
    if is_generated(source):
        return []
    scannable = strip_strings_and_comments(source)
    lines = source.split("\n")
    findings = []
    for match in SITE.finditer(scannable):
        line_index = scannable.count("\n", 0, match.start())
        is_fn = match.group("fn") is not None
        if justified(lines, line_index, is_fn):
            continue
        kind = "unsafe fn" if is_fn else "unsafe block"
        want = (
            "a `# Safety` rustdoc section or a `// SAFETY:` comment"
            if is_fn
            else "a `// SAFETY:` comment"
        )
        findings.append(
            f"{relative}:{line_index + 1}: {kind} without {want} "
            f"within {SAFETY_WINDOW} preceding lines"
        )
    return findings


def source_files() -> list[pathlib.Path]:
    crates = ROOT / "crates"
    if not crates.is_dir():
        raise SystemExit("crates/ does not exist")
    return sorted(
        path
        for crate in sorted(crates.iterdir())
        if crate.is_dir()
        for path in (crate / "src").rglob("*.rs")
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="check the checker against synthetic sources and exit",
    )
    parser.add_argument(
        "--fail",
        action="store_true",
        help="exit non-zero on any unjustified site (task 4.7 Step 3)",
    )
    parser.add_argument(
        "--max",
        type=int,
        default=None,
        metavar="N",
        help="exit non-zero only if the count exceeds N (ratchet mode)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print every finding (default: print only a per-crate summary)",
    )
    args = parser.parse_args(argv)
    if args.self_test:
        return self_test()

    findings: list[str] = []
    checked = 0
    generated = 0
    per_crate: dict[str, int] = {}
    for path in source_files():
        relative = str(path.relative_to(ROOT))
        source = path.read_text(encoding="utf-8", errors="replace")
        if is_generated(source):
            generated += 1
            continue
        checked += 1
        found = check_source(relative, source)
        if found:
            crate = path.relative_to(ROOT / "crates").parts[0]
            per_crate[crate] = per_crate.get(crate, 0) + len(found)
        findings.extend(found)

    if args.list:
        print("\n".join(findings))
    for crate, count in sorted(per_crate.items(), key=lambda kv: -kv[1]):
        print(f"  {count:5d}  {crate}")
    print(
        f"unsafe-safety lint: {len(findings)} unsafe site(s) without an adjacent "
        f"SAFETY justification across {checked} hand-written sources "
        f"({generated} generated sources skipped)"
    )

    if args.fail and findings:
        print(
            f"FAIL: {len(findings)} unjustified unsafe site(s)",
            file=sys.stderr,
        )
        return 1
    if args.max is not None and len(findings) > args.max:
        print(
            f"FAIL: {len(findings)} unjustified unsafe site(s) exceeds the "
            f"--max {args.max} ratchet",
            file=sys.stderr,
        )
        return 1
    if not args.fail and args.max is None:
        print("warn mode: not failing the build (task 4.7 Step 3 flips this)")
    return 0


def self_test() -> int:
    """Exercise the checker, including a planted unjustified block."""
    cases: list[tuple[str, str, int]] = [
        (
            "a file with no unsafe passes",
            "fn f() -> u32 { 7 }\n",
            0,
        ),
        (
            "a bare unsafe block is reported",
            "fn f() {\n    unsafe { g() }\n}\n",
            1,
        ),
        (
            "an unsafe block with an adjacent SAFETY comment passes",
            "fn f() {\n    // SAFETY: g's precondition holds here.\n"
            "    unsafe { g() }\n}\n",
            0,
        ),
        (
            "a SAFETY comment exactly three lines up still counts",
            "fn f() {\n    // SAFETY: holds.\n    #[allow(unused)]\n"
            "    let _x = 1;\n    unsafe { g() }\n}\n",
            0,
        ),
        (
            "a SAFETY comment four lines up is out of the window",
            "fn f() {\n    // SAFETY: holds.\n    #[allow(unused)]\n"
            "    let _x = 1;\n    let _y = 2;\n    unsafe { g() }\n}\n",
            1,
        ),
        (
            "a commented-out unsafe block is not a site",
            "fn f() {\n    // unsafe { g() }\n    let a = 1;\n}\n",
            0,
        ),
        (
            "a SAFETY comment two lines up counts",
            "fn f() {\n    // SAFETY: holds.\n    #[allow(unused)]\n"
            "    unsafe { g() }\n}\n",
            0,
        ),
        (
            "a SAFETY comment far above does NOT count",
            "fn f() {\n    // SAFETY: holds.\n    let a = 1;\n    let b = 2;\n"
            "    let c = 3;\n    unsafe { g() }\n}\n",
            1,
        ),
        (
            "a bare unsafe fn is reported",
            "pub unsafe fn f(p: *mut u8) { *p = 1; }\n",
            1,
        ),
        (
            "an unsafe fn with a # Safety rustdoc section passes",
            "/// Does a thing.\n///\n/// # Safety\n/// `p` must be valid.\n"
            "pub unsafe fn f(p: *mut u8) { *p = 1; }\n",
            0,
        ),
        (
            "a long doc block above # Safety still passes",
            "/// Line.\n/// Line.\n/// Line.\n/// Line.\n/// Line.\n"
            "/// # Safety\n/// `p` must be valid.\n/// More.\n/// More.\n"
            "/// More.\n/// More.\npub unsafe fn f(p: *mut u8) { *p = 1; }\n",
            0,
        ),
        (
            "an unsafe extern \"C\" fn is a site too",
            'pub unsafe extern "C" fn f(p: *mut u8) { }\n',
            1,
        ),
        (
            "a generated file is skipped entirely",
            "// @generated by the recompiler; DO NOT EDIT\n"
            "fn f() { unsafe { g() } }\n",
            0,
        ),
        (
            "a generated marker deep in the file does NOT excuse it",
            "fn f() { unsafe { g() } }\n" + "// filler\n" * 20
            + "// @generated\n",
            1,
        ),
        (
            "`unsafe {` inside a string literal is not a site",
            'const T: &str = "fn f() { unsafe { g() } }";\n',
            0,
        ),
        (
            "`unsafe {` inside a raw string literal is not a site",
            'const T: &str = r#"unsafe { g() }"#;\n',
            0,
        ),
        (
            "`unsafe` in a line comment is not a site",
            "// we used to write unsafe { g() } here\nfn f() {}\n",
            0,
        ),
        (
            "`unsafe` in a block comment is not a site",
            "/* unsafe { g() } */\nfn f() {}\n",
            0,
        ),
        (
            "unsafe impl and unsafe trait are not sites",
            "unsafe impl Send for T {}\nunsafe trait U {}\n",
            0,
        ),
        (
            "two unjustified blocks are both reported",
            "fn f() {\n    unsafe { g() }\n    unsafe { h() }\n}\n",
            2,
        ),
        (
            "a SAFETY comment justifies only the block it precedes",
            "fn f() {\n    // SAFETY: holds.\n    unsafe { g() }\n"
            "    let a = 1;\n    let b = 2;\n    unsafe { h() }\n}\n",
            1,
        ),
        (
            "a block-comment SAFETY line counts",
            "fn f() {\n    /* SAFETY: holds. */\n    unsafe { g() }\n}\n",
            0,
        ),
    ]

    failed = 0
    for label, source, expected in cases:
        found = check_source("<self-test>", source)
        if len(found) != expected:
            failed += 1
            print(
                f"SELF-TEST FAIL: {label}: expected {expected} finding(s), "
                f"got {len(found)}: {found}",
                file=sys.stderr,
            )
        else:
            print(f"SELF-TEST ok: {label}")

    if failed:
        print(f"{failed} self-test case(s) failed", file=sys.stderr)
        return 1
    print(f"unsafe-safety lint self-test: {len(cases)} cases passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
