// Generated by fn64-recomp-native (ELF/symbol front-end).
// Whole-program: inter-function JAL/J resolve to direct Rust calls.
// Typed Rust, no unsafe, no pointer casts.
#![allow(clippy::all, unused, non_snake_case)]
use fn64_recomp_native::{resolve_host_function, RecompContext, RecompFunc, Rdram};

// Recompiled from MIPS function `callee` @ 0x80001000 (3 instructions).
// Emitted by fn64-recomp-native (typed Rust, no unsafe).
#[allow(unused_variables)]
pub fn callee(ctx: &mut RecompContext, mem: &mut Rdram) {
    let mut pc: u32 = 0x80001000;
    'run: loop { match pc {
        0x80001000 => {
            // 0x80001000: Addiu { rt: 2, rs: 0, imm: 42 }
            ctx.set_r32(2, (0i32).wrapping_add(42));
            // 0x80001004: Jr { rs: 31 }
            // delay: 0x80001008: Nop
            // nop
            return;
        }
        _ => unreachable!("jumped to unmapped vram {:#X}", pc),
    } }
}

// Recompiled from MIPS function `caller` @ 0x80002000 (4 instructions).
// Emitted by fn64-recomp-native (typed Rust, no unsafe).
#[allow(unused_variables)]
pub fn caller(ctx: &mut RecompContext, mem: &mut Rdram) {
    let mut pc: u32 = 0x80002000;
    'run: loop { match pc {
        0x80002000 => {
            // 0x80002000: Jal { target: 1024 }
            ctx.set_r32(31, 0x80002008u32 as i32);
            // delay: 0x80002004: Addiu { rt: 4, rs: 0, imm: 7 }
            ctx.set_r32(4, (0i32).wrapping_add(7));
            callee(ctx, mem);
            pc = 0x80002008; continue 'run;
        }
        0x80002008 => {
            // 0x80002008: Jr { rs: 31 }
            // delay: 0x8000200C: Nop
            // nop
            return;
        }
        _ => unreachable!("jumped to unmapped vram {:#X}", pc),
    } }
}

// Recompiled from MIPS function `tail_caller` @ 0x80003000 (2 instructions).
// Emitted by fn64-recomp-native (typed Rust, no unsafe).
#[allow(unused_variables)]
pub fn tail_caller(ctx: &mut RecompContext, mem: &mut Rdram) {
    let mut pc: u32 = 0x80003000;
    'run: loop { match pc {
        0x80003000 => {
            // 0x80003000: J { target: 1024 }
            // delay: 0x80003004: Nop
            // nop
            callee(ctx, mem); return;
        }
        _ => unreachable!("jumped to unmapped vram {:#X}", pc),
    } }
}

// Safe LOOKUP_FUNC/get_function equivalent: sorted vram -> typed fn table.
static LOOKUP_TABLE: &[(u32, RecompFunc)] = &[
    (0x80001000, callee as RecompFunc),
    (0x80002000, caller as RecompFunc),
    (0x80003000, tail_caller as RecompFunc),
];

pub fn lookup(vram: u32) -> RecompFunc {
    if let Some(func) = resolve_host_function(vram) {
        return func;
    }
    match LOOKUP_TABLE.binary_search_by_key(&vram, |(addr, _)| *addr) {
        Ok(index) => LOOKUP_TABLE[index].1,
        Err(_) => panic!("lookup: no native function or host shim at vram {vram:#010X}"),
    }
}
