#!/usr/bin/env python3
"""Validate the typed unsupported-site registry and its source instrumentation."""

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "docs/unsupported-event-sites.json"
GENERATED_IDENTITY = (
    ROOT / "crates/fn64-runtime/src/unsupported_instrumentation_generated.rs"
)
INSTRUMENTATION_SCHEMA = "fn64.unsupported-instrumentation.v1"
SOURCE_ROOTS = [
    ROOT / "crates/fn64-runtime/src",
    ROOT / "crates/fn64-abi/src",
    ROOT / "crates/fn64-audio/src",
    ROOT / "crates/fn64-cpu-runtime/src",
    ROOT / "crates/fn64-render/src",
    ROOT / "crates/fn64-render-reference/src",
    ROOT / "crates/fn64-render-rt64/src",
]
CALL = re.compile(
    r"record_unsupported_event\(\s*[^,]+,\s*\"([^\"]+)\"", re.DOTALL
)
DYNAMIC_FORMAT_CALL = re.compile(
    r"record_unsupported_event\(\s*[^,]+,\s*format!\(\s*\"([^\"]+)\"",
    re.DOTALL,
)
HELPER_CALLS = (
    re.compile(r"render_unsupported_error\(\s*[^,]+,\s*\"([^\"]+)\"", re.DOTALL),
    re.compile(r"render_unsupported_panic\(\s*\"([^\"]+)\"", re.DOTALL),
    re.compile(r"\bunsupported\(\s*\"([^\"]+)\"", re.DOTALL),
)
RECORDED_OUTCOME_FORMS = (
    "record_unsupported_event",
    "trap_unsupported",
    "trap_unknown",
    "trap_unknown_vu",
    "trap_delay_slot_control",
    "unsupported_error",
    "unsupported_panic",
    "unsupported(",
)
OUTCOME_MACROS = re.compile(r"\b(panic|unimplemented|todo|format)!\s*\(")
TYPED_UNSUPPORTED_ERROR = re.compile(
    r"\bErr\s*\(\s*(?P<variant>(?:[A-Za-z_][A-Za-z0-9_]*::)*Unsupported[A-Za-z0-9_]*)\b",
    re.DOTALL,
)
UNSUPPORTED_OUTCOME = re.compile(
    r"\b(?:unsupported|unimplemented)\b|\bnot\s+(?:implemented|supported)\b",
    re.IGNORECASE,
)
VALID_SUBSYSTEMS = {"runtime", "abi", "audio", "recompiler", "render"}
VALID_DISPOSITIONS = {"loud_trap", "returned_error", "needs_lle"}


def push_bytes(wire: bytearray, value: str) -> None:
    encoded = value.encode("utf-8")
    wire.extend(len(encoded).to_bytes(8, "big"))
    wire.extend(encoded)


def instrumentation_wire(document: dict) -> bytes:
    """Encode the stable observable unsupported-event denominator.

    Paths and source triggers prove registry/source linkage in this checker,
    but do not change an event's observable identity. Excluding them keeps the
    release identity stable across a source-only relocation.
    """
    wire = bytearray()
    push_bytes(wire, INSTRUMENTATION_SCHEMA)
    families = sorted(document["families"], key=lambda family: family["operation_prefix"])
    wire.extend(len(families).to_bytes(8, "big"))
    for family in families:
        wire.append(0)
        push_bytes(wire, family["operation_prefix"])
        push_bytes(wire, family["subsystem"])
        dispositions = sorted(family["dispositions"])
        wire.extend(len(dispositions).to_bytes(8, "big"))
        for disposition in dispositions:
            push_bytes(wire, disposition)
    sites = sorted(document["sites"], key=lambda site: site["operation"])
    wire.extend(len(sites).to_bytes(8, "big"))
    for site in sites:
        wire.append(1)
        push_bytes(wire, site["operation"])
        push_bytes(wire, site["subsystem"])
        push_bytes(wire, site["disposition"])
    return bytes(wire)


def instrumentation_sha256(document: dict) -> bytes:
    return hashlib.sha256(instrumentation_wire(document)).digest()


def generated_identity_source(document: dict) -> str:
    digest = instrumentation_sha256(document)
    rows = []
    for offset in range(0, len(digest), 8):
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in digest[offset : offset + 8]))
    digest_source = ",\n".join(rows)
    return f'''// @generated by tools/check_unsupported_event_sites.py; do not edit by hand.\n\
pub const UNSUPPORTED_INSTRUMENTATION_SCHEMA: &str = "{INSTRUMENTATION_SCHEMA}";\n\
pub const UNSUPPORTED_INSTRUMENTATION_SHA256: [u8; 32] = [\n\
{digest_source},\n\
];\n'''


def brace_delta(line: str) -> int:
    """Count structural braces while ignoring quoted strings and line comments."""
    delta = 0
    quoted = None
    escaped = False
    index = 0
    while index < len(line):
        char = line[index]
        if quoted is not None:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quoted:
                quoted = None
            index += 1
            continue
        if line[index : index + 2] == "//":
            break
        if char == '"':
            quoted = char
        elif char == "'":
            # Rust lifetimes and labels (`'a`, `'_`, `'outer:`) are not
            # character literals. Treat an apostrophe as quoted syntax only
            # when the complete one-scalar/escaped character literal is
            # present on this line; otherwise braces later on the line must
            # still participate in cfg-item depth tracking.
            end = rust_char_literal_end(line, index)
            if end is not None:
                index = end + 1
                continue
        elif char == "{":
            delta += 1
        elif char == "}":
            delta -= 1
        index += 1
    return delta


def rust_char_literal_end(line: str, start: int) -> int | None:
    """Return the closing quote for a Rust char literal, not a lifetime."""
    index = start + 1
    if index >= len(line):
        return None
    if line[index] != "\\":
        closing = index + 1
        return closing if closing < len(line) and line[closing] == "'" else None

    index += 1
    if index >= len(line):
        return None
    if line[index] == "u" and index + 1 < len(line) and line[index + 1] == "{":
        closing_brace = line.find("}", index + 2)
        if closing_brace < 0:
            return None
        closing = closing_brace + 1
    elif line[index] == "x":
        closing = index + 3
    else:
        closing = index + 1
    return closing if closing < len(line) and line[closing] == "'" else None


def production_lines(text: str) -> list[tuple[int, str]]:
    """Drop complete items gated by cfg(test), including inline test modules."""
    output: list[tuple[int, str]] = []
    pending_test_item = False
    skipping = False
    saw_body = False
    depth = 0
    for lineno, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not skipping and stripped in {"#[cfg(test)]", "#[test]"}:
            pending_test_item = True
            continue
        if pending_test_item and not skipping:
            if stripped.startswith("#["):
                continue
            skipping = True
        if skipping:
            change = brace_delta(line)
            if change > 0:
                saw_body = True
            depth += change
            if (saw_body and depth <= 0) or (not saw_body and stripped.endswith(";")):
                pending_test_item = False
                skipping = False
                saw_body = False
                depth = 0
            continue
        output.append((lineno, line))
    return output


def macro_invocations(lines: list[tuple[int, str]]) -> list[tuple[int, int, str, str]]:
    """Return balanced outcome-macro calls as line-index spans and source text."""
    text = "\n".join(line for _, line in lines)
    invocations = []
    for match in OUTCOME_MACROS.finditer(text):
        depth = 1
        index = match.end()
        quoted = None
        escaped = False
        block_comment_depth = 0
        while index < len(text) and depth > 0:
            char = text[index]
            pair = text[index : index + 2]
            if block_comment_depth:
                if pair == "/*":
                    block_comment_depth += 1
                    index += 2
                    continue
                if pair == "*/":
                    block_comment_depth -= 1
                    index += 2
                    continue
                index += 1
                continue
            if quoted is not None:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == quoted:
                    quoted = None
                index += 1
                continue
            if pair == "//":
                newline = text.find("\n", index + 2)
                index = len(text) if newline < 0 else newline + 1
                continue
            if pair == "/*":
                block_comment_depth = 1
                index += 2
                continue
            if char == '"':
                quoted = char
            elif char == "'":
                end = rust_char_literal_end(text, index)
                if end is not None:
                    index = end + 1
                    continue
            elif char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            index += 1
        if depth != 0:
            continue
        start_line = text.count("\n", 0, match.start())
        end_line = text.count("\n", 0, index)
        if lines[start_line][1].lstrip().startswith(("//", "///", "//!")):
            continue
        invocations.append((start_line, end_line, match.group(1), text[match.start() : index]))
    return invocations


def unrecorded_outcomes(lines: list[tuple[int, str]]) -> list[tuple[int, str]]:
    """Find unsupported terminal/error construction that lacks a nearby recorder."""
    failures = []
    for start, end, macro, invocation in macro_invocations(lines):
        if macro not in {"unimplemented", "todo"} and not UNSUPPORTED_OUTCOME.search(invocation):
            continue
        window = "\n".join(
            candidate
            for _, candidate in lines[max(0, start - 12) : min(len(lines), end + 13)]
        )
        if not any(form in window for form in RECORDED_OUTCOME_FORMS):
            failures.append((lines[start][0], macro))
    return failures


def unrecorded_typed_unsupported_errors(
    lines: list[tuple[int, str]],
) -> list[tuple[int, str]]:
    """Find typed `Err(...::Unsupported*)` construction without a recorder."""
    text = "\n".join(line for _, line in lines)
    failures = []
    for match in TYPED_UNSUPPORTED_ERROR.finditer(text):
        if err_form_is_match_pattern(text, match.start()):
            continue
        start = text.count("\n", 0, match.start())
        end = text.count("\n", 0, match.end())
        window = "\n".join(
            candidate
            for _, candidate in lines[max(0, start - 12) : min(len(lines), end + 13)]
        )
        if not any(form in window for form in RECORDED_OUTCOME_FORMS):
            failures.append((lines[start][0], match.group("variant")))
    return failures


def err_form_is_match_pattern(text: str, start: int) -> bool:
    """Distinguish `Err(Unsupported(..)) =>` destructuring from construction."""
    opening = text.find("(", start)
    if opening < 0:
        return False
    depth = 0
    quoted = None
    escaped = False
    index = opening
    while index < len(text):
        char = text[index]
        if quoted is not None:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quoted:
                quoted = None
        elif char == '"':
            quoted = char
        elif char == "'":
            end = rust_char_literal_end(text, index)
            if end is not None:
                index = end
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return text[index + 1 :].lstrip().startswith("=>")
        index += 1
    return False


def dynamic_operation_prefix(format_string: str) -> str | None:
    """Return the stable prefix before a Rust format field, if one exists."""
    field = format_string.find("{")
    if field <= 0:
        return None
    return format_string[:field]


def registered_dynamic_operation_prefix(
    format_string: str, registered_prefixes: set[str]
) -> str | None:
    prefix = dynamic_operation_prefix(format_string)
    return prefix if prefix in registered_prefixes else None


def selftest(announce: bool = True) -> None:
    bad = production_lines(
        '''fn reject() {
    panic!(
        "operation is not implemented"
    );
}'''
    )
    assert unrecorded_outcomes(bad) == [(2, "panic")]

    bad_error = production_lines(
        '''fn reject() -> Result<(), String> {
    Err(format!(
        "unsupported command {opcode}"
    ))
}'''
    )
    assert unrecorded_outcomes(bad_error) == [(2, "format")]

    typed_error = production_lines(
        '''fn reject() -> Result<(), RenderError> {
    Err(RenderError::UnsupportedUcode { ucode_addr: 7 })
}'''
    )
    assert unrecorded_typed_unsupported_errors(typed_error) == [
        (2, "RenderError::UnsupportedUcode")
    ]

    recorded = production_lines(
        '''fn reject() {
    record_unsupported_event(
        UnsupportedSubsystem::Abi,
        "abi.test.rejected",
        "context",
        None,
        UnsupportedDisposition::LoudTrap,
    );
    panic!(
        "operation is unsupported"
    );
}'''
    )
    assert unrecorded_outcomes(recorded) == []
    assert unrecorded_typed_unsupported_errors(recorded) == []

    recorded_typed_error = production_lines(
        '''fn reject() -> Result<(), RenderError> {
    record_unsupported_event(
        UnsupportedSubsystem::Render,
        "render.test.unsupported-ucode",
        "context",
        None,
        UnsupportedDisposition::ReturnedError,
    );
    Err(RenderError::UnsupportedUcode { ucode_addr: 7 })
}'''
    )
    assert unrecorded_typed_unsupported_errors(recorded_typed_error) == []

    forwarding_match = production_lines(
        '''fn propagate(result: Result<(), StepFault>) -> Result<(), UnsupportedOp> {
    match result {
        Err(StepFault::Unsupported(op)) => return Err(op),
        _ => Ok(()),
    }
}'''
    )
    assert unrecorded_typed_unsupported_errors(forwarding_match) == []

    tests_only = production_lines(
        '''#[cfg(test)]
fn fixture() {
    panic!("unsupported fixture");
}
fn production() {}'''
    )
    assert unrecorded_outcomes(tests_only) == []
    tests_with_lifetimes = production_lines(
        '''#[cfg(test)]
mod tests {
    fn helper(value: &mut Result<&'_ str, &'static str>) {
        let brace = '{';
        panic!("unsupported lifetime fixture: {value:?} {brace}");
    }
}
fn production() {}'''
    )
    assert unrecorded_outcomes(tests_with_lifetimes) == []
    assert tests_with_lifetimes == [(8, "fn production() {}")]
    production_lifetime_macro = production_lines(
        '''fn reject<'a>(value: &'a str) {
    panic!("unsupported behavior: {}", helper::<'a>(value));
}'''
    )
    assert unrecorded_outcomes(production_lifetime_macro) == [(2, "panic")]
    production_char_macro = production_lines(
        '''fn reject(value: char) {
    panic!("unsupported character: {}", matches!(value, '('));
}'''
    )
    assert unrecorded_outcomes(production_char_macro) == [(2, "panic")]
    for literal in ["'('", "')'", r"'\''", r"'\\'", r"'\x28'", r"'\u{28}'"]:
        char_macro = production_lines(
            f'''fn reject() {{
    panic!("unsupported character: {{}}", {literal});
}}'''
        )
        assert unrecorded_outcomes(char_macro) == [(2, "panic")], literal
    typed_lifetime_construction = production_lines(
        '''fn reject<'a>(value: &'a str) -> Result<(), RenderError> {
    Err(RenderError::UnsupportedUcode(helper::<'a>(value, ')')))
}'''
    )
    assert unrecorded_typed_unsupported_errors(typed_lifetime_construction) == [
        (2, "RenderError::UnsupportedUcode")
    ]
    typed_lifetime_pattern = "Err(RenderError::UnsupportedUcode(helper::<'a>(')'))) =>"
    assert err_form_is_match_pattern(typed_lifetime_pattern, 0)
    assert dynamic_operation_prefix("abi.si.voice-command-{command:02x}") == (
        "abi.si.voice-command-"
    )
    assert dynamic_operation_prefix("render.static") is None
    dynamic_prefixes = {"abi.si.voice-command-", "abi.si.pif-command-"}
    assert registered_dynamic_operation_prefix(
        "abi.si.voice-command-{command:02x}", dynamic_prefixes
    ) == "abi.si.voice-command-"
    assert (
        registered_dynamic_operation_prefix(
            "abi.si.unregistered-command-{command:02x}", dynamic_prefixes
        )
        is None
    )

    identity_fixture = {
        "families": [
            {
                "operation_prefix": "render.",
                "subsystem": "render",
                "dispositions": ["returned_error", "loud_trap"],
            },
            {
                "operation_prefix": "abi.dynamic-",
                "subsystem": "abi",
                "dispositions": ["loud_trap"],
            }
        ],
        "sites": [
            {
                "operation": "runtime.test",
                "subsystem": "runtime",
                "disposition": "loud_trap",
            },
            {
                "operation": "audio.test",
                "subsystem": "audio",
                "disposition": "returned_error",
            }
        ],
    }
    reordered_fixture = {
        "sites": list(reversed(identity_fixture["sites"])),
        "families": [
            {
                **family,
                "dispositions": list(reversed(family["dispositions"])),
            }
            for family in reversed(identity_fixture["families"])
        ],
    }
    assert instrumentation_wire(identity_fixture) == instrumentation_wire(reordered_fixture)
    changed_fixture = json.loads(json.dumps(identity_fixture))
    changed_fixture["sites"][0]["disposition"] = "returned_error"
    assert instrumentation_sha256(identity_fixture) != instrumentation_sha256(changed_fixture)
    if announce:
        print("unsupported-event-sites selftest: ok")


def fail(message: str) -> None:
    print(f"unsupported-event-sites: {message}", file=sys.stderr)
    raise SystemExit(1)


def main() -> None:
    selftest(announce=False)
    document = json.loads(REGISTRY.read_text())
    if document.get("schema") != "fn64.unsupported-event-sites.v2":
        fail("wrong or missing schema")
    families = document.get("families")
    if not isinstance(families, list) or not families:
        fail("families must be a non-empty list")
    sites = document.get("sites")
    if not isinstance(sites, list) or not sites:
        fail("sites must be a non-empty list")
    registered: dict[str, dict[str, str]] = {}
    for index, site in enumerate(sites):
        required = {"operation", "subsystem", "disposition", "path", "trigger"}
        if set(site) != required:
            fail(f"site {index} fields differ from {sorted(required)}")
        operation = site["operation"]
        if operation in registered:
            fail(f"duplicate operation {operation!r}")
        if site["subsystem"] not in VALID_SUBSYSTEMS:
            fail(f"{operation}: invalid subsystem {site['subsystem']!r}")
        if site["disposition"] not in VALID_DISPOSITIONS:
            fail(f"{operation}: invalid disposition {site['disposition']!r}")
        path = ROOT / site["path"]
        if not path.is_file():
            fail(f"{operation}: missing source {site['path']}")
        text = "\n".join(line for _, line in production_lines(path.read_text()))
        if text.count(site["trigger"]) != 1:
            fail(f"{operation}: trigger must occur exactly once in {site['path']}")
        if text.count(f'"{operation}"') != 1:
            fail(f"{operation}: operation literal must occur exactly once in {site['path']}")
        registered[operation] = site

    family_operations: set[str] = set()
    family_prefixes: set[str] = set()
    dynamic_family_prefixes: set[str] = set()
    for index, family in enumerate(families):
        required = {
            "operation_prefix",
            "subsystem",
            "dispositions",
            "recorder_path",
            "recorder_trigger",
            "source_paths",
        }
        if set(family) != required:
            fail(f"family {index} fields differ from {sorted(required)}")
        prefix = family["operation_prefix"]
        subsystem = family["subsystem"]
        if subsystem not in VALID_SUBSYSTEMS:
            fail(f"family {index}: invalid subsystem {subsystem!r}")
        if not isinstance(prefix, str) or not prefix.startswith(f"{subsystem}."):
            fail(f"family {index}: operation_prefix must begin with {subsystem!r} plus '.'")
        if prefix in family_prefixes:
            fail(f"family {index}: duplicate operation_prefix {prefix!r}")
        dispositions = family["dispositions"]
        if (
            not isinstance(dispositions, list)
            or not dispositions
            or len(dispositions) != len(set(dispositions))
            or not set(dispositions) <= VALID_DISPOSITIONS
        ):
            fail(f"family {index}: dispositions must be a unique non-empty supported set")
        recorder = ROOT / family["recorder_path"]
        if not recorder.is_file():
            fail(f"family {index}: missing recorder {family['recorder_path']}")
        recorder_text = "\n".join(
            line for _, line in production_lines(recorder.read_text())
        )
        if recorder_text.count(family["recorder_trigger"]) != 1:
            fail(f"family {index}: recorder trigger must occur exactly once")
        source_paths = family["source_paths"]
        if not isinstance(source_paths, list) or not source_paths:
            fail(f"family {index}: source_paths must be non-empty")
        found = set()
        found_dynamic = set()
        for relative in source_paths:
            path = ROOT / relative
            if not path.is_file():
                fail(f"family {index}: missing source {relative}")
            text = "\n".join(line for _, line in production_lines(path.read_text()))
            for pattern_index, pattern in enumerate(HELPER_CALLS):
                operations = set(pattern.findall(text))
                if pattern_index == 2:
                    operations = {
                        operation for operation in operations if operation.startswith(prefix)
                    }
                found.update(operations)
            for format_string in DYNAMIC_FORMAT_CALL.findall(text):
                dynamic_prefix = dynamic_operation_prefix(format_string)
                if dynamic_prefix == prefix:
                    found_dynamic.add(dynamic_prefix)
        if not found and not found_dynamic:
            fail(f"family {index}: no literal helper operations or dynamic recorder found")
        wrong_prefix = sorted(operation for operation in found if not operation.startswith(prefix))
        if wrong_prefix:
            fail(f"family {index}: operations outside prefix: {wrong_prefix}")
        overlap = sorted(found & set(registered))
        if overlap:
            fail(f"family {index}: helper operations duplicate exact sites: {overlap}")
        family_operations.update(found)
        family_prefixes.add(prefix)
        dynamic_family_prefixes.update(found_dynamic)

    expected_generated = generated_identity_source(document)
    if not GENERATED_IDENTITY.is_file():
        fail(f"missing generated instrumentation identity {GENERATED_IDENTITY.relative_to(ROOT)}")
    if GENERATED_IDENTITY.read_text() != expected_generated:
        fail(
            "generated unsupported instrumentation identity is stale; run "
            "tools/check_unsupported_event_sites.py --write-generated"
        )

    observed: dict[str, str] = {}
    observed_dynamic: dict[str, str] = {}
    for root in SOURCE_ROOTS:
        for path in root.rglob("*.rs"):
            if path.name == "unsupported.rs":
                continue
            text = "\n".join(line for _, line in production_lines(path.read_text()))
            for operation in CALL.findall(text):
                relative = str(path.relative_to(ROOT))
                if operation in observed:
                    fail(f"{operation}: recorded in both {observed[operation]} and {relative}")
                observed[operation] = relative
            for format_string in DYNAMIC_FORMAT_CALL.findall(text):
                prefix = dynamic_operation_prefix(format_string)
                if prefix is None:
                    fail(
                        f"{relative}: dynamic unsupported operation format {format_string!r} "
                        "has no stable literal prefix"
                    )
                if (
                    registered_dynamic_operation_prefix(
                        format_string, dynamic_family_prefixes
                    )
                    is None
                ):
                    fail(
                        f"{relative}: unregistered dynamic unsupported operation family "
                        f"{format_string!r}"
                    )
                if prefix in observed_dynamic:
                    fail(
                        f"dynamic family {prefix!r}: recorded in both "
                        f"{observed_dynamic[prefix]} and {relative}"
                    )
                observed_dynamic[prefix] = relative

    missing = sorted(set(registered) - set(observed))
    extra = sorted(set(observed) - set(registered))
    if missing or extra:
        fail(f"registry/source mismatch: missing={missing}, unregistered={extra}")
    for operation, relative in observed.items():
        if registered[operation]["path"] != relative:
            fail(
                f"{operation}: registry path {registered[operation]['path']} != source {relative}"
            )

    missing_dynamic = sorted(dynamic_family_prefixes - set(observed_dynamic))
    if missing_dynamic:
        fail(f"registered dynamic families have no recorder: {missing_dynamic}")

    # Sweep the loud shapes most likely to bypass the typed source. Balanced
    # macro extraction keeps multiline panic/error construction visible while
    # cfg(test) items, comments, enum declarations, and assertions stay out.
    for root in SOURCE_ROOTS:
        for path in root.rglob("*.rs"):
            relative = path.relative_to(ROOT)
            if (
                path.name == "unsupported.rs"
                or "tests" in relative.parts
                or ("src" in relative.parts and "bin" in relative.parts)
            ):
                continue
            for lineno, macro in unrecorded_outcomes(production_lines(path.read_text())):
                fail(
                    f"{relative}:{lineno}: unsupported {macro}! outcome "
                    "bypasses a typed recorder"
                )
            for lineno, variant in unrecorded_typed_unsupported_errors(
                production_lines(path.read_text())
            ):
                fail(
                    f"{relative}:{lineno}: typed unsupported error {variant} "
                    "bypasses a typed recorder"
                )
    print(
        "unsupported-event-sites: ok "
        f"({len(sites)} exact sites, {len(family_operations)} literal family operations, "
        f"{len(family_prefixes)} operation families, "
        f"{len(dynamic_family_prefixes)} dynamic)"
    )


if __name__ == "__main__":
    if sys.argv[1:] == ["--selftest"]:
        selftest()
    elif sys.argv[1:] == ["--write-generated"]:
        document = json.loads(REGISTRY.read_text())
        GENERATED_IDENTITY.write_text(generated_identity_source(document))
        print(
            "unsupported-event-sites: wrote "
            f"{GENERATED_IDENTITY.relative_to(ROOT)}"
        )
    elif sys.argv[1:] == ["--print-instrumentation-sha256"]:
        document = json.loads(REGISTRY.read_text())
        print(instrumentation_sha256(document).hex())
    elif sys.argv[1:]:
        fail(
            "usage: check_unsupported_event_sites.py "
            "[--selftest|--write-generated|--print-instrumentation-sha256]"
        )
    else:
        main()
