//! B2 grading-only cross-check for WM2000/NWXE's resident boot bank.
//!
//! The answer key is mechanically extracted from the `entry` and
//! `main_1050` sections of
//! `aki-recomp/games/NWXE/syms/dump.toml`. That file is generated by
//! `aki_profile.gen_symbols` from the splat/spimdisasm output in
//! `games/NWXE/disasm/asm/1000.s` and `1050.s`; each function row carries
//! its exact `vram` and `size`. The fixture records those rows verbatim as
//! `(name, va_start, size)`. It is consumed only here, after discovery, and
//! never enters the root set or any other pipeline input.
//!
//! Exact sizes matter for NWXE: unlike OoT's contiguous linker-map key,
//! NWXE's generated symbol catalog has gaps between some function extents.
//! Treating the next symbol start as the preceding function's end would turn
//! those gaps into fabricated ground truth.

use crate::partition::Owner;
use std::collections::BTreeSet;

/// VAs reached by a direct `jal`, and therefore mechanically proven callable
/// entries even if the answer key groups them inside a coarser function.
pub type JalTargets = BTreeSet<u32>;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnswerFunction {
    pub name: String,
    pub va_start: u32,
    pub size: u32,
}

impl AnswerFunction {
    pub fn va_end(&self) -> u32 {
        self.va_start.wrapping_add(self.size)
    }
}

#[derive(Debug)]
pub struct ParsedFunctionKey {
    pub functions: Vec<AnswerFunction>,
    pub skipped: Vec<String>,
}

/// Parse the fixture's `name,va_start,size` format. Comment lines beginning
/// with `#` carry provenance and are intentionally ignored; every other
/// malformed data row is returned in `skipped`, never silently discarded.
pub fn parse_function_csv(csv: &str) -> ParsedFunctionKey {
    let mut functions = Vec::new();
    let mut skipped = Vec::new();

    for line in csv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line == "name,va_start,size" {
            continue;
        }

        let fields: Vec<_> = line.split(',').map(str::trim).collect();
        if fields.len() != 3 {
            skipped.push(line.to_string());
            continue;
        }
        let (Ok(va_start), Ok(size)) = (
            u32::from_str_radix(fields[1], 16),
            u32::from_str_radix(fields[2], 16),
        ) else {
            skipped.push(line.to_string());
            continue;
        };
        if size == 0 {
            skipped.push(line.to_string());
            continue;
        }
        functions.push(AnswerFunction {
            name: fields[0].to_string(),
            va_start,
            size,
        });
    }

    functions.sort_by_key(|f| f.va_start);
    ParsedFunctionKey { functions, skipped }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FunctionGrade {
    /// Discovery produced an owner rooted at the exact answer-key start.
    MatchedExact,
    /// Discovery reached the function start inside a coarser owner.
    MatchedCoarse { owner_root: u32 },
    /// No discovered owner covers this answer-key function start.
    Open,
    /// Discovery split the answer-key extent at a proven direct-call target.
    InteriorEntry { owner_root: u32 },
    /// Discovery invented an interior root that no direct call proves.
    WrongSplit { owner_root: u32 },
}

#[derive(Debug, Clone)]
pub struct FunctionGradeReport {
    pub total: usize,
    pub matched_exact: usize,
    pub matched_coarse: usize,
    pub interior_entries: usize,
    pub open: usize,
    pub wrong: usize,
    pub per_function: Vec<(String, FunctionGrade)>,
}

impl FunctionGradeReport {
    pub fn matched_fraction(&self) -> f64 {
        if self.total == 0 {
            return 0.0;
        }
        (self.matched_exact + self.matched_coarse) as f64 / self.total as f64
    }
}

/// Grade discovered owners against exact NWXE function extents. Missing
/// functions stay `Open`; only an unproven root strictly inside a known
/// extent is `WrongSplit`.
pub fn grade_functions(
    owners: &[Owner],
    answer_key: &[AnswerFunction],
    jal_targets: &JalTargets,
) -> FunctionGradeReport {
    let owner_roots: BTreeSet<u32> = owners.iter().map(|o| o.root_va).collect();
    let mut matched_exact = 0;
    let mut matched_coarse = 0;
    let mut interior_entries = 0;
    let mut open = 0;
    let mut wrong = 0;
    let mut per_function = Vec::with_capacity(answer_key.len());

    for function in answer_key {
        let start = function.va_start;
        let end = function.va_end();
        let split_owners: Vec<_> = owners
            .iter()
            .filter(|owner| owner.root_va > start && owner.root_va < end)
            .collect();
        if let Some(owner) = split_owners
            .iter()
            .find(|owner| !jal_targets.contains(&owner.root_va))
        {
            wrong += 1;
            per_function.push((
                function.name.clone(),
                FunctionGrade::WrongSplit {
                    owner_root: owner.root_va,
                },
            ));
            continue;
        }
        if let Some(owner) = split_owners.first() {
            interior_entries += 1;
            per_function.push((
                function.name.clone(),
                FunctionGrade::InteriorEntry {
                    owner_root: owner.root_va,
                },
            ));
            continue;
        }

        if owner_roots.contains(&start) {
            matched_exact += 1;
            per_function.push((function.name.clone(), FunctionGrade::MatchedExact));
            continue;
        }

        match owners
            .iter()
            .find(|owner| owner.root_va <= start && owner.extent_end > start)
        {
            Some(owner) => {
                matched_coarse += 1;
                per_function.push((
                    function.name.clone(),
                    FunctionGrade::MatchedCoarse {
                        owner_root: owner.root_va,
                    },
                ));
            }
            None => {
                open += 1;
                per_function.push((function.name.clone(), FunctionGrade::Open));
            }
        }
    }

    FunctionGradeReport {
        total: answer_key.len(),
        matched_exact,
        matched_coarse,
        interior_entries,
        open,
        wrong,
        per_function,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn owner(root: u32, end: u32) -> Owner {
        Owner {
            bank: "boot".to_string(),
            root_va: root,
            block_starts: vec![root],
            extent_end: end,
        }
    }

    #[test]
    fn parses_real_fixture_with_exact_resident_count_and_no_skips() {
        let parsed = parse_function_csv(include_str!("../testdata/nwxe_boot_functions.csv"));
        assert!(parsed.skipped.is_empty(), "skipped: {:?}", parsed.skipped);
        assert_eq!(parsed.functions.len(), 847);
        assert_eq!(parsed.functions[0].va_start, 0x8000_0400);
        assert_eq!(parsed.functions[0].size, 0x3c);
        assert_eq!(parsed.functions.last().unwrap().va_start, 0x8004_8fb8);
    }

    #[test]
    fn exact_root_and_coarse_cover_are_matches() {
        let key = vec![
            AnswerFunction {
                name: "a".into(),
                va_start: 0x8000_0000,
                size: 0x10,
            },
            AnswerFunction {
                name: "b".into(),
                va_start: 0x8000_0010,
                size: 0x10,
            },
        ];
        let report = grade_functions(&[owner(0x8000_0000, 0x8000_0020)], &key, &JalTargets::new());
        assert_eq!(report.matched_exact, 1);
        assert_eq!(report.matched_coarse, 1);
        assert_eq!(report.wrong, 0);
    }

    #[test]
    fn unproven_interior_root_is_wrong_but_jal_target_is_valid() {
        let key = vec![AnswerFunction {
            name: "a".into(),
            va_start: 0x8000_0000,
            size: 0x10,
        }];
        let owners = vec![
            owner(0x8000_0000, 0x8000_0008),
            owner(0x8000_0008, 0x8000_0010),
        ];
        let wrong = grade_functions(&owners, &key, &JalTargets::new());
        assert_eq!(wrong.wrong, 1);

        let mut jal_targets = JalTargets::new();
        jal_targets.insert(0x8000_0008);
        let valid = grade_functions(&owners, &key, &jal_targets);
        assert_eq!(valid.wrong, 0);
        assert_eq!(valid.interior_entries, 1);
    }

    #[test]
    fn a_gap_after_an_exact_extent_is_not_fabricated_as_coverage() {
        let key = vec![AnswerFunction {
            name: "after_gap".into(),
            va_start: 0x8000_0020,
            size: 0x10,
        }];
        let report = grade_functions(&[owner(0x8000_0000, 0x8000_0010)], &key, &JalTargets::new());
        assert_eq!(report.open, 1);
    }
}
